### ISSUE TITLE
Why Shift+Insert is not working properly on Firenvim?

### ISSUE THREAD

**Issue by rafaelmuynarsk** [glacambre/firenvim#1067]
- OS Version: linux x86-64
- Browser Version:  Firefox 89.0
- Browser Addon Version: 0.2.7
- Neovim Plugin Version: 0.2.7

Let's say I copy to the clipboard the following javascript code:

```
for(var i =0; i <= 100; i++){
    console.log("test" + i)
}
```
If I try to paste it on Firenvim with `Shift+Insert` I see the following result:

```
for(var i =0; i 
```

I've tried deactivating all other plugins and configurations inside my init.vim file, but this behavior is always the same when I'm using Firenvim, even when I'm with a minimalistic install. However, if I open NeoVim from the operating system and I type `Shift+Insert` this bug doesn't happen and it pastes everything that is inside my clipboard, so the issue really seems to be with Firenvim. Is there any workaround for this issue?

**Comment by glacambre** [comment]
That's probably because Firenvim intercepts the event and sends it to neovim as `<S-Insert>`. You can verify this by entering insert mode, pressing `<C-v>` and then `Shift+Insert` to see if that what's happening.

If `<S-Insert>` is inserted in the buffer, then the workaround is rather simple, `:nnoremap <S-Insert> "+p` and `:inoremap <S-Insert> <C-r>+` should do the trick.

I'm ambivalent about what the right behavior is here. Respecting OS keyboard shortcuts sounds like the right thing to do, but making as many keyboard shortcuts as possible available to Neovim is appealing too.

**Comment by rafaelmuynarsk** [comment]
When I use `"+p` and `<C-r>+` directly on the Firenvim that is open it does the trick... However, both mapping it directly on the file :nnoremap <S-Insert> "+p and :inoremap <S-Insert> <C-r>+ or using these two lines inside my `init.vim` file doesn't work as well... On insert mode I see the same result and in command mode it prints ` (` in my example... 

The same behavior happens when pressing `<C-v>` and then `Shift+Insert`, I see the result I showed on my question.

**Comment by glacambre** [comment]
Huh, that's weird. Does using `:set paste` change anything before pressing `<S-Insert>` in insert mode? What about `:set nopaste`?

**Comment by glacambre** [comment]
Closing this issue as it's been awaiting feedback from its author for more than a month. If you're still experiencing this issue, please go through the instructions I gave in my previous message, tell me what the result is and I'll re-open :)
