### ISSUE TITLE
Cant paste text from buffer

### ISSUE THREAD

**Issue by HappyCthulhu** [glacambre/firenvim#1182]
Hi! Im trying to paste text from buffer via Shift+Ctrl+v. Is it possible?
If it is, how can i do it? 
If not, can u hix this?

**Comment by glacambre** [comment]
`Shift+Ctrl+v` is not a neovim keyboard shortcut. It's a terminal keyboard shortcut.

Neovim's keyboard shortcut for pasting from the OS clipboard is `"+p`. If you want to use `Ctrl+Shift+v` to paste in Firenvim, you'll need to remap it like this: `nnoremap <C-S-v> "+p`. See https://github.com/glacambre/firenvim/issues/551 for more information about pasting.

**Comment by danielb2** [comment]
`:registers` will tell you what the buffers are in general

**Comment by vitaly-zdanevich** [comment]
> `nnoremap <C-S-v> "+p`

Added this to `~/.config/vim/init.vim` but on Ctrl-Shift-v it paste `^` and on second press `<C-S-V>` :(

Also tested on incognito window without other extensions.

Firefox.

**Comment by alerque** [comment]
@vitaly-zdanevich You just created a *normal mode* binding (nmap), but you appear to be trying to use it in *insert mode* (imode). That won't work because it will conflict with VIM's <kbd>Ctrl</kbd><kbd>V</kbd> binding for inserting a literal chacacter instead of interpreting input as an escape sequence. Hence why you are getting a different result the second press (the literal escape sequence).

If you want an insert mode binding, create an insert mode binding. Note you'll have to use `<C-r>+` as the action instead of `"+p`

```vim
inoremap <C-S-v> <C-r>+
```

Note none of this has to do with Firenvim, this is just creating a new insert mode binding and mapping it to the usual way VIM/NeoVIM expects an insert-mode paste to be initiated.
