### ISSUE TITLE
:echo "<long msg>" during Nvim startup causes "Neovim is not responding"

### ISSUE THREAD

**Issue by justinmk** [glacambre/firenvim#1196]
- OS Version: macos 11.6
- Browser Version: chrome 93
- Browser Addon Version: 0.2.10
- Neovim Plugin Version: b5a75b8bc9d3565d339145f94f21f0864b757858

### What I tried to do

1. my init.vim has a long `:echo` message under some conditions, which causes a "hit enter" prompt.
    - `:echo 'x x x x x x x x x x x xx x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x x '` 
2. if this "echo" takes places, firenvim fails to activate and claims "neovim is not responding"

This seems unnecessarily fragile, given that Nvim waits for UI to attach before printing messages, and the UI has full control to check `nvim_get_mode()` and/or send ctrl-c or ENTER to clear any messages on startup.

**Comment by glacambre** [comment]
>This seems unnecessarily fragile, given that Nvim waits for UI to attach before printing messages, 

It doesn't, `nvim --headless -u /tmp/init.vim` will `echo` your messages immediately to stdout (even if `call stdioopen()` has already been called). This pollutes the communication channel between the browser and neovim and makes the browser kill neovim. Unfortunately there's nothing I can do about this on the browser side, the communication protocol between the browser and neovim is out of reach for webextensions.

I don't think I can do anything on the neovim side either. Perhaps `dup()` stdout, close the original file descriptor to prevent Neovim from using it, let the user's config load and `write()` to the dup'ed file descriptor to send the user's config to the browser? Not sure if this would work on osx/windows...

**Comment by glacambre** [comment]
>First question is why use --headless instead of --embed

Because `--embed` makes neovim interpret stdin as a msgpack-RPC chaannel but stdin is actually a stream of JSON objects preceded by four bytes representing the size of the JSON object. Webextensions can't use any other protocol to communicate with native programs.

>Shall we keep this issue open to track the discussion?

Sure. This is a true annoyance with Firenvim and I'd love to make it go away.

>Should stdioopen() change Nvim's behavior?

I think this would help Firenvim a lot. As far as github search shows, I'm the only person who ever used stdioopen in a plugin and uploaded it to github, so this might be a fairly safe change wrt backwards compatibility.

**Comment by glacambre** [comment]
In the specific case of this issue, there is no need to express the fact that you are also experiencing this problem as I already did everything that I could to solve it, we just need a neovim maintainer to merge [this PR](https://github.com/neovim/neovim/pull/15910) in order to make it go away for good.

In the more general sense, I think that yes, adding an eyes or thumbs-up emoji is usually the approach I take when I want to say "I have this issue too" without bothering the people subscribed to the issue :).

**Comment by glacambre** [comment]
I merged a change that should make firenvim work even when the user's init.vim emits messages (and once https://github.com/neovim/neovim/pull/17199 is merged it'll also bypass press-enter prompts!) so this is basically done - firenvim is ready and neovim 0.7.0 will work flawlessly no matter how broken user configs are :)
