### ISSUE TITLE
optionally run with "nvim -u NORC"

### ISSUE THREAD

**Issue by justinmk** [glacambre/firenvim#1209]
It's common that users have Nvim config or system/environment issues.  It's a shame that firenvim has to say "sorry, Nvim isn't responding". I would guess that most users would rather just have something that works, even if it doesn't load their config.

So for cases when "Nvim isn't responding", but firenvim _knows_ that `nvim --api-info` (or whatever) most certainly _does_ work, firenvim could present a button like `Load Nvim without user config`. This would give a great experience for the many users who otherwise are likely discouraged by having to troubleshoot. And it's _much_ better than having nothing at all.

 (Related: is it possible for firenvim to show the startup errors? Or at least hyperlink to the TROUBLESHOOT.md, from the firenvim browser button.)

related:

- https://github.com/glacambre/firenvim/issues/1198
- https://github.com/glacambre/firenvim/issues/1196

**Comment by glacambre** [comment]
Running neovim with different flags or catching errors both mean doing pretty complicated things (e.g. JSON parsing) in the shell/batch script the browser runs in order to start neovim. I think it'd be much easier to rely on the stdioopen change described in #1196 for this. I plan on submitting a PR to neovim for this soon-ish.

Adding an hyperlink to the browser button is a pretty good idea though. I've done this in #1210.

**Comment by glacambre** [comment]
Not needed anymore (and impossible to implement anyway) as Firenvim will forward neovim's error messages to users once neovim 0.7.0 is released :)
