### ISSUE TITLE
Add a .firevimrc

### ISSUE THREAD

**Issue by Julian** [glacambre/firenvim#121]
I'm filing this even having seen #21 to see whether the below makes sense --

I haven't fully played with the g:firenvim_config setting, but I *think* it
seems to do something slightly different than what I expected.

There's 2 things -- configuring firenvim's behavior itself (which it seems like
firenvim_config controls) but then there's also "nvim settings that are
specific to what to do when it's running in a browser / under firenvim" -- and
the latter seems like it'd be nice to support?

As a concrete example, I have `set laststatus=2` normally, but within firenvim
I want `set laststatus=0`, because status bars aren't that useful for me in
this use case.

There are a few other settings I can imagine there.

So it seems like it'd still be useful to either have a separate config file
that's sourced only in firenvim, or otherwise to have a way (if there isn't one
already that I've missed) to notice that the init.vim is being sourced inside
firenvim.

Lemme know if I've missed this and it exists already!

**Comment by glacambre** [comment]
I think you might be able to use [UIEnter](https://github.com/neovim/neovim/pull/6917), nvim_list_uis() and nvim_get_chan_info() in order to detect whether firenvim is connected. I'll look into this.

**Comment by justinmk** [comment]
UIEnter was provided to avoid the need for every UI to have a special config file. If firenvim calls nvim_set_client_info then one can also handle ChanInfo event.

Hmm, it might be good if UIEnter exposed the channel name in v:event...

**Comment by glacambre** [comment]
I published a new firenvim version on addons.mozilla.org and the chrome webstore. This version correctly calls set_client_info before attaching the UI, which means you can use the process described [here](https://github.com/glacambre/firenvim#configuring-neovims-behavior) in order to set settings only for firenvim. I stole this code from @BlueDrink9's [post](https://github.com/glacambre/firenvim/issues/123#issuecomment-536242113).

**Comment by Julian** [comment]
Awesome!
