### ISSUE TITLE
Thunderbird add-on doesn't work with stable version

### ISSUE THREAD

**Issue by rlcintra** [glacambre/firenvim#1272]
The current stable version of Thunderbird is 91.4.0, however the add-on can only be installed on 92.0 or later.

Is there a reason the Thunderbird add-on doesn't target the stable version?

Thank you!

**Comment by glacambre** [comment]
Yes, Firenvim relies on some fix that happened in later versions.

There's no point in you moving to Thunderbird betas or me attempting to port to 91.4.0 though as the thunderbird maintainers broke Firenvim again in recent thunderbird betas (see #1263 / https://bugzilla.mozilla.org/show_bug.cgi?id=1746468 ).

I'll close this issue but feel free to ask any other question you may have :).

**Comment by rlcintra** [comment]
Hopefully the version 92 will become stable soon enough. Thanks @glacambre .

**Comment by glacambre** [comment]
I wouldn't recommend using Firenvim on thunderbird, be it on 92.0 or any other version until https://bugzilla.mozilla.org/show_bug.cgi?id=1746468 is fixed, otherwise you're going to spend a bit of time setting things up/getting used to Firenvim only to see it yanked away from you when thunderbird 95/96 gets released :/.
