### ISSUE TITLE
Embedding firenvim in a website

### ISSUE THREAD

**Issue by kovasap** [glacambre/firenvim#1329]
Just out of curiosity, is it possible to use firenvim not as a browser plugin, but instead as a component I can embed in a website?  For instance, could I make a website that opens up as a nvim instance and let's users edit some text that is then e.g. saved on a backend server.  Another way to think about this idea is Google docs, but using firenvim as the editing frontend.

Or maybe there are other projects that try to accomplish this?

**Comment by glacambre** [comment]
>is it possible to use firenvim not as a browser plugin, but instead as a component I can embed in a website?

In theory, yes. You could grab the browser extension's input handler and renderer and put them in a website. When loaded, the website opens a websocket, on websocket connections the server execs a new neovim instance running neovim with the firenvim plugin loaded and wham, you've got an embedded neovim in your website!

However, I wouldn't recommend doing that. Running one neovim instance per user on your server can't possibly scale, especially since these instances need to be able to execute arbitrary code with no way to bound execution time. A better approach would be to embed libnvim as a wasm module directly in the browser, but that's far, far more work.

I'm not aware of any projects that do this for now, but I do plan on working on that someday (when I manage to clear my project backlog :D). I'll close this issue, but feel free to ask any other question you may have :)

**Comment by kovasap** [comment]
Ok thanks for the detailed response.  I think the wasm thing is more what I
was thinking of.
