### ISSUE TITLE
TextArea becomes split with NerdTree 

### ISSUE THREAD

**Issue by rafaelbdb** [glacambre/firenvim#1333]
- OS Version: linux x86-64
- Browser Version: Google Inc. Chrome 99.0.4844.51
- Browser Addon Version: 0.2.12
- Neovim Plugin Version: 

### What I tried to do
Enter a TextArea to type with FireNVim in GoogleChrome.

### What happened
The TextArea becomes divided in two. I guess this is because I have the `NerdTree Plugin` installed in my NeoVim (which I don't intend to disable).

![image](https://user-images.githubusercontent.com/3081776/157740759-f98c7b1d-c381-4e2c-8883-78249469d27f.png)

It's annoying to have to type `:q` once, every time I enter a TextArea.

### What should happen
The TextArea should **always** show only one file/area, as HTML TextAreas are single.

**Comment by glacambre** [comment]
This doesn't happen with a Neovim config that only loads Firenvim, so this is a setup issue on your end that only you can fix. What you can do to figure out what's causing this is to remove lines from your config and restart Firenvim until the problem disappears.

**Comment by rafaelbdb** [comment]
Makes no sense to ask people to change their WORKING TOOL config only to conform to a browser addon. The addon should adapt, or have an independent config.

**Comment by glacambre** [comment]
>Makes no sense to ask people to change their WORKING TOOL config only to conform to a browser addon. The addon should adapt, or have an independent config.

Makes no sense to ask people to change their WORKING PROJECT only to conform to the settings of a single user. The user should adapt, or have an independent config (and yes, you can have an independent config, just read [the README](https://github.com/glacambre/firenvim#building-a-firenvim-specific-config).

I also tried to reproduce your issue, by the way. It doesn't happen when just loading Firenvim and NerdTree. The problem is in your config and you're the only one who can fix it. Please, next time you open an issue for any project on any platform, provide a working reproducer. Otherwise you're just wasting everybody's time.
