### ISSUE TITLE
$NVIM_LISTEN_ADDRESS will be removed in Nvim 0.8

### ISSUE THREAD

**Issue by justinmk** [glacambre/firenvim#1357]
https://github.com/neovim/neovim/pull/11009 (Nvim 0.8+) will change Nvim so that $NVIM_LISTEN_ADDRESS is _not_ passed to child processes.  After that, the correct way to detect a "host" or "parent" Nvim is to check for $NVIM env var: this means the current process is a child of Nvim.

The old $NVIM_LISTEN_ADDRESS env var had conflicting purposes as both a parameter ("the current process should _listen on_ this address") and a descriptor ("the current process is a _child of_ this address").

Perhaps that ambiguity caused this issue: https://github.com/glacambre/firenvim/commit/0ceb758df301cee633e083eaa2c3a3d56a5f0880

**Comment by glacambre** [comment]
Thanks for the warning, @justinmk. I didn't realize it at the time but this change breaks firenvim - the neovim plugin part of Firenvim needs to connect to its own neovim instance over the unix socket in order to forward the messages received over the TCP socket from the client.

What would you recommend as the new way for plugins to figure out what the $NVIM_LISTEN_ADDRESS of the current process is?

**Comment by glacambre** [comment]
Ah, I can use v:servername. Sorry for bothering you!

**Comment by justinmk** [comment]
Thanks, sorry for the trouble here!
