### ISSUE TITLE
Neovim inserts null character ^@ at first line in p5js editor

### ISSUE THREAD

**Issue by christofferaakre** [glacambre/firenvim#1359]
- OS Version: Ubuntu 20.04
- Browser Version: Google Chrome Version 101.0.4951.64 (Official Build) (64-bit)
- Browser Addon Version: 0.2.12
- Neovim Plugin Version: Sorry, not sure how to find this

### What I tried to do
Tried to use firenvim on https://editor.p5js.org/
### What happened
Neovim does not engage automatically as the p5js editor does not use a textarea. This is expected.
Using firenvim still works, however it for some reason puts a null character at the start of the editor,
i.e. at line 1, column 1. If I copy the character and paste it into my terminal, it shows as `^@`, which
is indeed a null character. This causes a syntax error in the JavaScript code I am typing in the editor,
and I end up having to remove it manually everytime I `:wq`.

To be clear, this does not seem to happen elsewhere, I've only had this happen on p5js so far.

**Comment by glacambre** [comment]
Thanks for the report. It's slightly surprising as p5js is using CodeMirror, which Firenvim already supports. I'll dig deeper when I have time.

**Comment by dclong** [comment]
I'm having the same issue when editing files using FireNVim on GitHub.

**Comment by glacambre** [comment]
@dclong what browser, os and neovim version are you using?

**Comment by dclong** [comment]
OS: Ubuntu 20.04
Browser: Chrome 102.0.5005.61 
NeoVim: 0.4.3

**Comment by glacambre** [comment]
@dclong please update your neovim, your are several stable versions behind.

**Comment by dclong** [comment]
@glacambre,

I'm seeing the same issue in another environment too.
OS: macOS Monterey (12.4)
Browser: Chrome 102.0.5005.61
NeoVim: 0.7.0

**Comment by dclong** [comment]
The same issue is observed on 
- Ubuntu 22.04 / !Pop OS 22.04
- Chrome 106.0.5249.119 (Official Build) (64-bit)
- NeoVim 0.7.2

**Comment by jedenastka** [comment]
Not sure if this is the same issue, but I am getting identical behaviour with the [Minecraft Wiki](https://minecraft.wiki) editor. I can also confirm this happens to me in the linked p5js example.

My setup:

- Debian Unstable (up to date as of now)
- Firefox 126.0 (from Debian)
- Neovim 0.10.0
- Firenvim 0.2.16

**Comment by glacambre** [comment]
@jedenastka Thanks for the ping, I can repro the problem on p5js now.

**Comment by glacambre** [comment]
Problem seems to come from https://github.com/glacambre/firenvim/blob/fc72687977e1c34259c42f0e408655cf2638760d/src/FirenvimElement.ts#L522 , we successfuly set CodeMirror's content and then trigger a key event to update any UI that might rely on a keypress event to update, but CodeMirror interprets this as a keypress for the null byte. We can't get rid of the keypress event, so we need to find a way to make CodeMirror understand it should ignore it...

**Comment by glacambre** [comment]
We actually have many possible hacks to pick from:
```js
function onKeyPress(e) {
    var cm = this;
    if (e.target && e.target != cm.display.input.getField()) { return }
    if (eventInWidget(cm.display, e) || signalDOMEvent(cm, e) || e.ctrlKey && !e.altKey || mac && e.metaKey) { return }
    var keyCode = e.keyCode, charCode = e.charCode;
    if (presto && keyCode == lastStoppedKey) {lastStoppedKey = null; e_preventDefault(e); return}
    if ((presto && (!e.which || e.which < 10)) && handleKeyBinding(cm, e)) { return }
    var ch = String.fromCharCode(charCode == null ? keyCode : charCode);
    // Some browsers fire keypress events for backspace
    if (ch == "\x08") { return }
    if (handleCharBinding(cm, e, ch)) { return }
    cm.display.input.onKeyPress(e);
  }
```
So
1) Send the keypress event to another element, to make codemirror earlyreturn. Not sure that would work, because this might be exactly the element the website would be listening to.
2) Make `signalDOMEvent(cm, e)` return true. Very enticing as this function looks like this:
```js
  function signalDOMEvent(cm, e, override) {
    if (typeof e == "string")
      { e = {type: e, preventDefault: function() { this.defaultPrevented = true; }}; }
    signal(cm, override || e.type, cm, e);
    return e_defaultPrevented(e) || e.codemirrorIgnore
  }
```
So in theory setting this additional attribute to true should work, but... In practice the event object gets cleaned up when it goes from the extension's context to the page's context, meaning that the attribute is lost, and so codemirror does not ignore the event. This could likely be fixed by executing the patching of the event + call to dispatchEvent from the page's context, but then this would break the editors that don't require page execution on websites that have a strict CSP. Not good.

3) Make it an empty ctrl/alt press. Likely to work? Hopefully no websites decides to enter a special state on an empty ctrl/alt press.
4) Make the keypress event be a backspace event. No good, websites might decide to delete things despite codemirror ignoring the event.
5) Make handleCharBinding do nothing and return true. Seems complicated, many diverging paths, no obvious solution there.

I think I'll pick 3) and then fall back to 2) if it proves problematic.
