### ISSUE TITLE
Add documentation for enabling firenvim for GMail

### ISSUE THREAD

**Issue by Julian** [glacambre/firenvim#137]
I think this is likely a common use case, so filing it as a feature request --

Specifically, out of the box, firenvim does not enable for the GMail (inline) compose window. 

It looks like GMail uses an editable div element, so bit odd, but not insane presumably (though what do I know about HTML).

I think it'd be great either if this worked out of the box, or if not, to just document a reasonable selector setup that'd have this work in GMail (it seems like that might just be e.g. div.editable maybe scoped to gmail.com or whatever, but yeah needs verification).

**Comment by glacambre** [comment]
I don't have a gmail account and google asks for a phone number when I try to create one so I won't be able to do this :/

You could try this: open the page console (`<CS-I>` on firefox/chrome), type a few letters and then evaluate `document.activeElement` in the console. This should tell you what element firenvim needs to add focus listeners to. On chrome you can right click on the element and copy its selector, on firefox you need to click on the small icon next to the element and then right click the element in the inspector in order to do that.

**Comment by danihodovic** [comment]
I would be interested in this.

**Comment by alexriedl** [comment]
In my very limited testing I got the following to work most of the time:
```
\ 'mail.google.com*': {
    \ 'selector': 'div[role="textbox"]',
    \ 'priority': 1,
\ },
```

**Comment by alexriedl** [comment]
I can't get newlines to work correctly though. Finding a solution to that would make it perfect.

**Comment by glacambre** [comment]
Thanks for investigating and posting your findings :).

I think the reason newlines do not work is that contenteditable elements expect `<br/>` elements instead of newlines. Fixing this might just be a matter of using innerText/innerHTML instead of textContent [here](https://github.com/glacambre/firenvim/blob/109de0b70d50ff523ee35d32b406b9aecd39f6dc/src/page/functions.ts#L136). I'll try to reproduce and fix this issue with another contenteditable element.

**Comment by glacambre** [comment]
I added @alexriedl's example config to firenvim's defaults and replaced textContent with innerText, this worked well enough on outlook and so I hope it also works on gmail. You can test this by building from source or wait for a new release :)
