### ISSUE TITLE
"Neovim is not responding" with vivaldi in firejail

### ISSUE THREAD

**Issue by larskotthoff** [glacambre/firenvim#1412]
- OS Version: Arch Linux
- Browser Version: Vivaldi 5.3.2679.73-1
- Browser Addon Version: 0.2.13
- Neovim Plugin Version: 0.2.13

I'm trying to get firenvim working with the browser running in firejail. It works fine outside firejail, but when I run the browser in it, I get "Neovim is not responding" without any other information. I have verified that nvim is started, but it doesn't produce any output. Comparing `lsof` output with and without firejail, it looks like it can't create a TCP socket to listen on when run inside the firejail. Further, the unix socket has no connections to it when inside the firejail.

Here's the relevant part of the firejail config:

    noblacklist ${HOME}/.config/nvim
    noblacklist ${HOME}/.vim
    noblacklist ${HOME}/.local/share/nvim
    noblacklist ${HOME}/.local/share/firenvim
    whitelist ${HOME}/.config/nvim
    whitelist ${HOME}/.vim
    whitelist ${HOME}/.local/share/nvim
    whitelist ${HOME}/.local/share/firenvim

    noblacklist /usr/share/nvim
    whitelist /usr/share/nvim

    include allow-lua.inc

Any pointers would be appreciated -- happy to provide more information.

**Comment by glacambre** [comment]
I don't know firejail and could not find any information about getting logs from it when it disallows an opperation, so I can't really help you. My generic advice would be to start with the most permissive config possible (not disallowing anything) and progressively getting more restrictive, until you find what makes Firenvim fail.

You could also try to run the whole thing under strace (firejail seems to require a [specific setup for this](https://github.com/netblue30/firejail/wiki/Debugging-Firejail)), logging all syscalls, and observing the ones that are failing in order to get an understanding of what could be going on.

I'm going to close this issue because there's no change for me to make in Firenvim, but do not take this as meaning that the conversation should end, I can answer more questions if you have them :)

**Comment by larskotthoff** [comment]
Thanks, I'll try to investigate and if I find a solution I'll post it here.
