### ISSUE TITLE
turning off autocompletion?

### ISSUE THREAD

**Issue by gilbh** [glacambre/firenvim#1414]
This is a question:

I am trying to disable all autocompletion when using firenvim but I am still getting it:
![image](https://user-images.githubusercontent.com/39532610/186148426-bd56641c-34e0-4a66-8825-df27d2921a9e.png)

I didn't find what "[A]" stands for in the suggestion list, anyone knows?

When I try to disable CoC:
```
let g:coc_enabled=0
```
-- nothing happens, and when I try:
```
execute "CocDisable"
```
-- firenvim `Reload settings` command generates this error, as if CoC is not loaded, which I don't understand why:
![image](https://user-images.githubusercontent.com/39532610/186147905-7bb34cb1-dbf6-4dea-b169-466f22710349.png)

Any help would be greatly appreciated!

Thanks

**Comment by gilbh** [comment]
Thanks. My init.vim is very minimal:
```

**Comment by glacambre** [comment]
>My init.vim is very minimal:

It's not minimal at all, `set runtimepath=...`, `let packpath=...` and `source ~/.vimrc` each can load a massive amount of plugins. We even have proof this is happening: the snippet you posted does not load Firenvim, but Firenvim has to be loaded in order to work, and Firenvim works on your machine :).

`:verbose set omnifunc` might give you a hint about where the autocompletion is coming from. If it does not, I would recommend removing everything (e.g. `rm -rf ~/.vim ~/.vimrc ~/.config/nvim ~/.local/share/nvim ~/.local/state/nvim`) and doing a clean install step by step from scratch.

**Comment by gilbh** [comment]
You are, of course, correct! (my .vimrc runs over a 1,000 lines of code ... ;-)

I will work with your suggestions (and try to post elsewhere on that mysterious `[A]`). 

Thanks a lot.
