### ISSUE TITLE
Use a clean nvim

### ISSUE THREAD

**Issue by taDachs** [glacambre/firenvim#1415]
hello,
is there a way to use firenvim with a clean nvim? Most of my plugins are very specific for programming, therefore they results in more problems than they are worth while using firenvim in the browser.

Something like the `nvim --clean` option would be nice. Another way would be something like an option for setting the config used by firenvim. Is this possible?

**Comment by alerque** [comment]
There are plenty of options available already to implement this yourself, but how exactly you do that might depend on your config type (vimscript or lua) and what plugin manager you are using. Mine only loads plugins related to the filetype set anyway, so what I get in Firenvim is usually quite relevant. I have a few extra config options that get set or unset when entering a firenvim ui.

Half the point of Firenvim for me is to get *my* editor with *my* config. IF you don't want something in *your* config I would suggest using your config to exclude any Firenvim instances from loading those bits.

**Comment by glacambre** [comment]
@taDachs Building a firenvim-specific config can be done as described [here](https://github.com/glacambre/firenvim#building-a-firenvim-specific-config). You can do anything in there, source files, enable or disable plugins... If you have an init.lua, the code is almost the same, you can just check if `vim.g.started_by_firenvim` is `nil` or `true`.

I'll close this issue because there's nothing to do on the Firenvim side :).

Off-topic: @alerque I saw you merged the PR that enables extending lunarmodules/busted, thanks a lot for this, I've been waiting for it for a while :)
