### ISSUE TITLE
Incrementing font size

### ISSUE THREAD

**Issue by Manzanit0** [glacambre/firenvim#144]
- OS Version: OSX Mojave
- Browser Version: Brave, Version 0.69.132 Chromium: 77.0.3865.90 (Official Build) (64-bit)
- What I tried to do: Edit some text
- What happened: The font size is very small compared to the rest of the browser
- What I expected: Normal fontsize

![Screenshot 2019-10-10 at 09 57 21](https://user-images.githubusercontent.com/10437518/66554301-a9c3dd80-eb44-11e9-93e1-2d72fcda2528.png)

I'm not sure if it has to do with my setup of nvim, or with the plugin. Any ideas?

**Comment by glacambre** [comment]
Oh, cool to see that firenvim works as is in Brave :)

Firenvim currently uses the browser's default font size. If you're using a version built from from source, you can follow [these instructions](https://github.com/glacambre/firenvim/issues/110#issuecomment-538744163) in order to change your font/its size. If you're using a pre-built version from the chrome store, you'll have to wait for me to push a new release :).

**Comment by Manzanit0** [comment]
Ah, sounds like I'll have to wait then 😝

Thanks for the quick response! Cheers!

**Comment by glacambre** [comment]
I released a new version for both chrome and firefox. Upgrade to firenvim 0.1.11 and use `:h guifont` to be able to change your font and its size.
