### ISSUE TITLE
Setting cmdline to "neovim" doesn't disable firenvim's external cmdline

### ISSUE THREAD

**Issue by odrling** [glacambre/firenvim#1442]
- OS Version: Gentoo Linux
- Browser Version: Firefox 106.0.1
- Browser Addon Version: 0.2.13
- Neovim Plugin Version: 2f0ee858c3eb5c9d306523cc054047eda2e6a3a2

### What I tried to do

I am trying to disable the external cmdline from firenvim so I can use the interface from [noice.nvim](https://github.com/folke/noice.nvim) instead.

I've set the local settings:

```lua
vim.g.firenvim_config = {localSettings = {
    [".*"] = {cmdline = "neovim", priority = 0, takeover = "never"},
    ["https://[^/]*github\\.com/.*"] = {cmdline = "neovim", priority = 1, takeover = "always"}}}
```

### What happened

Firenvim's cmdline appears on top of Noice's: ![](https://hikari.butaishoujo.moe/p/7c4695a6/Screenshot%202022-10-25%2018:42:24.png)

**Comment by glacambre** [comment]
Hi, thanks a lot for the interesting bug report :).

The settings you provided *do* disable Firenvim's command line, the problem is that Noice [re-enables it](https://github.com/folke/noice.nvim/blob/c2f37ed040238573e7a2542e14a814b2c19164bd/lua/noice/ui/init.lua#L24). This is a fundamental issue at the neovim level: Noice attaches to Neovim and pretends to be a UI, but Neovim does not support providing different command line representations to differents UIs.

The workaround for current Firenvim versions is to only enable Noice when `g:started_by_firenvim` does not exist or is false. Ultimately I could provide a `cmdline: "none"` setting to prevent Firenvim from rendering the command line, but the proper solution really is at the neovim-level itself.

Nice colorscheme btw :)

**Comment by alerque** [comment]
I was just struggling with this one myself the other day too. I've been trying to get *noice* spun up in my own config, but having trouble with it in two places: Firenvim and Neovide (Rust based graphical wrapper).

I am able to disable it for the places it is trouble of course, but it would be nice to actually use with Firenvim. As such the mentioned `cmdline: "none"` option be nice to have.

**Comment by glacambre** [comment]
`"cmdline":"none"` is now implemented in the latest releases, which have been published. The new release is already available on addons.mozilla.org and will be automatically published on the chrome web store once it passes review.
