### ISSUE TITLE
Website CSP applies to webextension and force-upgrades websocket

### ISSUE THREAD

**Issue by alerque** [glacambre/firenvim#145]
This plugin is fantastic and I'm looking forward to using it universally in the future. However it looks like it needs some massaging before it works across the board. I'm typing this Github issue in it now (and other than the fact that this is the third time I'm typing this because <kbd>Ctrl</kbd><kbd>W</kbd> is deeply embeded muscle memory) it works fine here. But the very next place I tried it was on Stack Overflow. For example the [ask form](https://stackoverflow.com/questions/ask) has an input ... that launches this plugin but doesn't actually work. The input gets surrounded by a black boarder on focus that wasn't there before, but the NeoVim instance never appears inside it.

It is not clear how to either disable the plugin for that site so I can continue to use the original input or fix it so that it actually works. Obviously the latter would be preferred, but some sort of plugin configuration should probably be introduced to cover cases where it is undesired as well.

Neovim 0.4.3 and Firefox 69.0.2 on Arch Linux.

**Comment by glacambre** [comment]
Thank you for reporting this bug, I'll try to fix it this week-end/next week.

I could probably add a way to disable `<C-w>` for chrome with https://github.com/glacambre/firenvim/issues/103. If you use firefox you can also patch your browser with https://github.com/glacambre/firefox-patches. Maybe I should also re-enable swap file support so that users can try to `:recvoer` their lost data.

You can disable firenvim in a tab by clicking on its icon next to the urlbar. If you'd rather disable it on a domain, you can add the following declaration to your init.vim:

```
let g:firenvim_config = {
    \ 'localSettings': {
        \ '.*': {
            \ 'selector': 'textarea',
            \ 'priority': 0,
        \ },
        \ 'regex-matchin-the-domain-names-where-firenvim-should-be-disabled': {
            \ 'selector': '',
            \ 'priority': 1,
        \ }
    \ }
\ }
```

**Comment by glacambre** [comment]
Stackoverflow's CSP is force-upgrading my websocket connections to TLS. There's nothing I can do about that (at least not without risking being banned by Mozilla).
We'll have to wait until https://bugzilla.mozilla.org/show_bug.cgi?id=1267027 is fixed :/

**Comment by alerque** [comment]
Could we just setup the websocket to _be_ TLS?

**Comment by glacambre** [comment]
This would add a large maintenance burden that I'm not willing to deal with for now (browsers don't want self-signed certificates, using a let's encrypt cert would require users to update every three months, I don't want to give money to CAs…). I'd rather help mozilla fix their bug (but I probably won't do that because the few times I sent them patches I couldn't even get a review).
Adding TLS would also make creating neovim frames slightly slower/more CPU intensive (although I'm not sure it would be noticeable) for no added security benefits so I really don't want to do that.

I would be willing to merge a PR that adds optional, opt-in TLS support though. In order to implement such a thing one would probably need to update [firenvim#install](https://github.com/glacambre/firenvim/blob/69a863dfeb7c336a2c740ea637d81c62fb54727a/autoload/firenvim.vim#L231) to have it add a self-signed cert to the browser's/os certificate store and then udate the [websocket implementation](https://github.com/glacambre/firenvim/blob/69a863dfeb7c336a2c740ea637d81c62fb54727a/lua/websocket.lua#L41) to deal with TLS. After than, one could add a tls setting [defaulting to false](https://github.com/glacambre/firenvim/blob/69a863dfeb7c336a2c740ea637d81c62fb54727a/src/background.ts#L106) and check the state of that setting when [creating the websocket](https://github.com/glacambre/firenvim/blob/69a863dfeb7c336a2c740ea637d81c62fb54727a/src/nvimproc/Neovim.ts#L18).

But really, I'd rather see the bugzilla bug fixed :).

**Comment by alerque** [comment]
My experience with Bugzilla suggests, at just four years old, this bug is just starting to wind up it's lifecycle. I've been poking at what workarounds might exist but it's not promising. Adding a TLS updgade option on the Neovim side is probably the only way in the next few years this will work :-(

**Comment by infokiller** [comment]
I just tried to Stackoverflow form and it seems to work correctly for me: the `<input>` fields do not invoke firenvim (but this is intentional right?), but the `<textarea>` (for the question body) does it.
Running latest version from master branch.

**Comment by alerque** [comment]
@infokiller Could that have to do with #252?

**Comment by glacambre** [comment]
Note to self: there's an `about:config` preference named `network.websocket.allowInsecureFromHTTPS`. Perhaps setting it to true could be enough to make Firenvim work on stackoverflow?

**Comment by alerque** [comment]
@glacambre I gave that a quick trial and it doesn't seem to help.

**Comment by glacambre** [comment]
Ah, too bad. Thanks for trying it out :)

**Comment by glacambre** [comment]
Note to self: Trying to downgrade the websocket by using the webRequest API doesn't work.

**Comment by glacambre** [comment]
Hi everyone. If you're brave enough to compile Firefox yourselves, you can apply [this patch](https://github.com/glacambre/firefox-patches/blob/master/fix-webextension-websocket-upgrades.patch) to Firefox's sources to make it stop force-upgrading websockets. This will prevent Firefox from breaking Firenvim on stackoverflow.
I'll send this patch to Mozilla but don't get excited, I'm fairly certain it'll never get reviewed, just like the other patches I've sent before.

**Comment by glacambre** [comment]
This is now fixed in Firefox nightly. I was right about my patch never being reviewed, but wrong about the bug never being fixed. A big thank you to Mozilla for taking care of this!

**Comment by alerque** [comment]
If I'm reading Bugzilla right this is targeted for release in Firefox 92.
