### ISSUE TITLE
overriding site-specific takeover config from file

### ISSUE THREAD

**Issue by dmfay** [glacambre/firenvim#1452]
I use firenvim on multiple machines/contexts and prefer to keep specific sites external instead of blobbing them all together in my dotfiles. This is a working solution to read lines like `meet.google.com:never` from a .gitignorable file and apply them to firenvim's localSettings. It's a little hacky and it'd be nice if there's a way for the plugin itself to load the file from a consistent-across-platforms location, but I'm mostly putting this up as a recipe. Thanks for the plugin!

```lua
local config = {
  globalSettings = {...},
  localSettings = {
    ['.*'] = {
      takeover = 'once',
    },
  },
}

local f = io.open(vim.fs.normalize('~/.vim/plugins/fire.nvim.sites'), 'r')

if f ~= nil then
  for line in f:lines() do
    for site, t in string.gmatch(line, '([^:]+):(.+)') do
      config.localSettings[site] = { takeover = t }
    end
  end
end

vim.g.firenvim_config = config
```

**Comment by glacambre** [comment]
Hi, thanks for posting your solution :)

> it'd be nice if there's a way for the plugin itself to load the file from a consistent-across-platforms location

This is already pretty easy to do in "pure" neovim:
```lua
vim.cmd("luafile " .. vim.fn.stdpath("config") .. "/local-firenvim-configuration")
```
With local-firenvim-configuration being a lua file that would either define or tweak an already existing vim.g.firenvim_config, so I don't really feel adding more code to Firenvim for this would be worth it, especially since Firenvim's userbase is rather small and has very different aesthetic preferences/needs.

I'll close this issue, but thanks for opening it :)
