### ISSUE TITLE
Lost focus on livebook

### ISSUE THREAD

**Issue by drselump14** [glacambre/firenvim#1498]
- OS Version: MacOS Ventura
- Browser Version: Firefox 109.0.1
- Browser Addon Version: 0.2.14
- Neovim Plugin Version: latest

### What I tried to do

Try editing on Monaco editor on Livebook

### What happened

Firenvim can't get the focus, and I need to click outside the frame and click the frame again to get the focus.
It only happens on Livebook, Monaco editor on https://microsoft.github.io/monaco-editor/ works fine.
Do you have any idea what's the issue? Or please give me some advice to debug the issue.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/1251454/216183532-5bd83870-7f03-4441-85ad-1a3a7ea19dac.gif)

**Comment by glacambre** [comment]
Open the firefox debugger, find the Firenvim sources, open the file named FirenvimElement.ts and place a breakpoint on the first line of the constructor and then trigger Firenvim:

![20230202_07h26m20s_grim](https://user-images.githubusercontent.com/11534587/216249011-3c768fec-427c-49a0-b494-a80dfb1dc92c.png)

When hovering your mouse over `elem`, you will know what element Firenvim is attaching to. You need to figure out a unique CSS selector for this element (if you're lucky you can use the element's `#id`, otherwise you'll have to compute a path using parents and CSS classes), and then use this selector as described in [Configuring what elements Firenvim should appear on](https://github.com/glacambre/firenvim#configuring-what-elements-firenvim-should-appear-on).

**Comment by drselump14** [comment]
Looks like it's some compatibility issue with the livebook javascript code (https://github.com/livebook-dev/livebook/issues/1681) . So I will close this issue. Thanks for your help

**Comment by glacambre** [comment]
Oh, looks like I had completely misunderstood your issue, sorry about that. Indeed, I don't think Firenvim can do much more here.
