### ISSUE TITLE
Chrome support ?

### ISSUE THREAD

**Issue by iamcco** [glacambre/firenvim#15]
Is it possible to support chrome ?

**Comment by glacambre** [comment]
Yes, it's possible and planned. However I want to get Firenvim's architecture right before porting it to Chrome - the current architecture is rather slow and I want to improve that first.

**Comment by glacambre** [comment]
Hi, I've finally added Chrome support in a051f39. For now you'll have to build it yourself, I'll provide a pre-built version on the chrome store once neovim 0.4.0 is released (firenvim needs some of its APIs).

Please note that there currently is a rather frustrating bug (#26) that sometimes prevents writing the content of neovim's buffers to the textarea you're editing. In order to help recovering what you wrote, firenvim will keep a file in `$HOME/.local/share/firenvim` with your text.

**Comment by iamcco** [comment]
Awesome! Thank you

**Comment by theniceboy** [comment]
NVim 4.0 was just released! Can’t wait!

**Comment by glacambre** [comment]
I submitted Firenvim to the chrome web store Monday morning, it has been rejected because the reviewer couldn't figure out how to install or use it (the email I received was extremely vague). I submitted it again and am waiting for another review :/.

**Comment by theniceboy** [comment]
@glacambre wow the reviewer doesn’t know nvim and firenvim? Someone needs some general ed!

Thank you for the good work! Can’t wait!

**Comment by glacambre** [comment]
Firenvim has been accepted on the Chrome Web store! You can find out how to install it [here](
https://github.com/glacambre/firenvim#pre-built).

**Comment by theniceboy** [comment]
Thank you so much!!!!!!
Thank you so much!!!!!!
Thank you so much!!!!!!
Thank you so much!!!!!!
Thank you so much!!!!!!
Thank you so much!!!!!!
Thank you so much!!!!!!
Thank you so much!!!!!!
Thank you so much!!!!!!
Thank you so much!!!!!!
Thank you so much!!!!!!

**Comment by theniceboy** [comment]
Thank you so so so much!!!

[This](https://gph.is/g/Z8nVz8n) is what the web browsing experience should have been!

(Deleted the previous comment to avoid spam lol)
