### ISSUE TITLE
Firenvim automatically turn on after opening terminal

### ISSUE THREAD

**Issue by TroySigX** [glacambre/firenvim#1519]
- OS Version:
- Browser Version: brave 1:1.48.171-2
- Browser Addon Version: 0.2.14
- Neovim Plugin Version: 0.2.14

### What I tried to do
completely exit firenvim after typing `:q`

### What happened
After I typed `:q`, then switch tab and finally go back to the original tab, firenvim kept showing up even though I didn't trigger it.

To be specific, here are the steps I did:
1. Turn on firenvim
2. type something
3. `:q`
4. click in the text field (where I previously typed)
5. go to another tab
6. go back to the original tab

After the 6th step, firenvim automatically turns on.

**Comment by TroySigX** [comment]
I also tried with google chrome (version 111.0.5563.64-1) and it behaved exactly the same.

**Comment by glacambre** [comment]
This happens because the textarea is being focused again, which triggers Firenvim again. You might want to set the [`takeover` setting to `once`](https://github.com/glacambre/firenvim#configuring-firenvim-to-not-always-take-over-elements), which would ensure Firenvim only triggers once per textarea. An alternative could be to set it to `never` and then only trigger Firenvim through its keyboard shortcut.

I'm going to close this issue because everything is working as expected here, but feel free to ask more questions :)

**Comment by glacambre** [comment]
I suspect that your `config.firenvim` is not being loaded, otherwise you would be getting an error due to `vim.g.firenvim_config` not existing. You need to define the whole object.

**Comment by TroySigX** [comment]
Thanks @glacambre! For those who need, here's my config:

```
    {
        'glacambre/firenvim',

        cond = not not vim.g.started_by_firenvim,
        build = function()
            require('lazy').load({ plugins = 'firenvim', wait = true })
            vim.fn['firenvim#install'](0)
        end,
        config = function()
            vim.g.firenvim_config = {
                  globalSettings = { alt = "all" },
    l             localSettings = {
                       [".*"] = {
                           cmdline  = 'neovim',
                           content  = 'text',
                           priority = 0,
                           selector = 'textarea',
                           takeover = 'never'
                        }
                   }
             }
        end,
    },

**Comment by alerque** [comment]
Running `require("foo")` in Lua will *NOT* necessarily run the code in foo, it will make sure it has been loaded once at some point. It almost definitely will not run it when you want it to, especially when you are dealing with lazy-loading plugin managers. It might just be stuffed in the module preloader somewhere, but it is up to you to actually do something with it.

Lua has other functions for this, such as `loadfile()` that will actually execute a Lua file in place.

That being said the more traditional way to handle this would be to return a closure:

```lua
    {
        'glacambre/firenvim',
        cond = not not vim.g.started_by_firenvim,
        build = function()
            require('lazy').load({ plugins = 'firenvim', wait = true })
            vim.fn['firenvim#install'](0)
        end,
        config = require('config.firenvim')
    },
```

And the config file:

```lua
return function ()
	vim.g.firenvim_config.localSettings['.*'] = { takeover = 'never' }
end
```

This ensures that the code will get *run*, not just loaded.

Also you could keep the original structure and use `require("config.firenvim")()` (note trailing parents) to execute it, but since what you need is the function to give as a callback anyway just passing the function works.

**Comment by TroySigX** [comment]
Thank you ver much for yor comment, @alerque !
