### ISSUE TITLE
Plugin not loading and not installing

### ISSUE THREAD

**Issue by maarinku** [glacambre/firenvim#1546]
- OS Version: Windows 11
- Browser Version: Brave 1.52.130
- Browser Addon Version: 0.2.14
- Neovim Plugin Version: Unknown

### What I tried to do
I'm trying to just install it, but I'm using NVChad and Lazy with it.
### What happened
It initially set up the keys and everything for Firenvim when I first put the code in my init.lua file, same as any other plugin I'd put in, but the call function doesn't work, and it's set as "Disabled" in my :Lazy menu. The troubleshooting guide says it's likely an issue on my part, but I can't see where I've messed up, I'm at a complete loss. I haven't even touched any of the config files for the plugin either. It is possible that I may be forgetting something, as it has been a while since I've installed any plugins with neovim.

**Comment by glacambre** [comment]
Hi, thanks for opening this issue. Does `git clone`'ing the repo somewhere on your disk and then replacing all of your init.lua with the following piece of code change anything?
```lua
vim.opt.rtp:append("/path/to/cloned/firenvim")
```

**Comment by jxyyz** [comment]
I didn't investigate this issue deeply – but I'm also using NVChad.

This Lazy entry seems to be working well:
```
  {
    'glacambre/firenvim',

    -- Lazy load firenvim
    cond = not not vim.g.started_by_firenvim,
    build = function()
      require("lazy").load({ plugins = "firenvim", wait = true })
      vim.fn["firenvim#install"](0)
    end,
    lazy = false,
  },
```
**Close nvim and restart browser after all.**

- in normal nvim session plugin appears as "disabled"
- in browser works totally fine

**I'm uncertain if this is the correct solution and if it definitely works 100% (or if it's just my case) because I only spent 20 minutes searching for a solution and didn't verify why the error appears.**

**Comment by maarinku** [comment]
> I didn't investigate this issue deeply – but I'm also using NVChad.
> 
> This Lazy entry seems to be working well:
> 
> ```
>   {
>     'glacambre/firenvim',
> 
>     -- Lazy load firenvim
>     cond = not not vim.g.started_by_firenvim,
>     build = function()
>       require("lazy").load({ plugins = "firenvim", wait = true })
>       vim.fn["firenvim#install"](0)
>     end,
>     lazy = false,
>   },
> ```
> 
> **Close nvim and restart browser after all.**
> 
> * in normal nvim session plugin appears as "disabled"
> * in browser works totally fine
> 
> **I'm uncertain if this is the correct solution and if it definitely works 100% (or if it's just my case) because I only spent 20 minutes searching for a solution and didn't verify why the error appears.**

This worked for some reason. I think I just needed the `lazy = false` bit, which wasn't specified in the original docs, thank you!

**Comment by glacambre** [comment]
The installation instructions needed to be upgraded due to a change in lazy.nvim. This has been done in https://github.com/glacambre/firenvim/pull/1553/files .

**Comment by feoh** [comment]
The only way I was able to get this working with Neovim latest on either MacOS
or Linux with Lazy.nvim was:

- Comment out the lazy= line in the configuration snippet provided. Thus
firenvim is loaded and the install will run.
- Ignore the one liner shell invocation to run the bild/install and instead
simply run nvim and `:call firenvim#install(0)` from within Neovim. Do this for
every browser you want to use firenvim with.
- Test that firenvim works
- Uncomment the lazy= line, because now that the install has run this works as
desired.

If I can find time to dig into the code a bit more I'll contribute an install instruction update PR. I'd suggest avoiding the one liner entirely. If you can use Neovim you can run an :invocation :)

**Comment by glacambre** [comment]
@feoh What you're describing is surprising to me as, as far as I understand from reading Lazy.nvim's docs, firenvim#install should have been called by lazy.nvim regardless of whether firenvim is marked as lazy-loaded (although I don't know what lazy-loaded means here...). Perhaps the `build` function should be replaced with `":call firenvim#install(0)"`? :thinking:

**Comment by feoh** [comment]
The key distionction here is that lazy will only load if the plugin is
'require'-d :)

This forum post: https://github.com/folke/lazy.nvim/discussions/463 has all the details including a require line that fixes the problem. It also shows the correct syntax for crafting a firenvim_config for lazy which I struggled with as well :)

**Comment by glacambre** [comment]
>The key distionction here is that lazy will only load if the plugin is 'require'-d :)

I still don't understand :sob: . Lazy.nvim's documentation says:

>build is executed when a plugin is installed or updated. Before running build, a plugin is first loaded. 

So what does "loaded" mean here?

**Comment by feoh** [comment]
lazy.nvim's documentation is quite - how do I put this diplomatically - challenging :)

The key is the phrase I pointed you at previously in that if the plugin isn't 'require'-d it's not loaded, and thus isn't available to be :lua call'd.

Honestly I stumble over lazy.nvim configuration all the time. It's VERY unclear to me for any plugin's setup where any particular thing should go. opts = ? config =? Can I get away with just a table or does it want a function() ?
