### ISSUE TITLE
Shows "loading configs" all the time

### ISSUE THREAD

**Issue by benlieb** [glacambre/firenvim#1552]
My browser plugin says "loading configs" all of the time. Even when I haven't loaded, and after re-loading them manually. 

![image](https://github.com/glacambre/firenvim/assets/634562/69440e6b-4920-4daa-a211-7bd28a35aedc)

**Comment by glacambre** [comment]
That's because your neovim emits "loading configs" on stdout or stderr when your browser starts it. If you run `grep -ri "loading configs" ~/.config/nvim ~/.local/share/nvim ~/.local/state/nvim` you should find the file that contains this string and be able to make it stop emitting this message :)

I'll close this issue because there's nothing to do for me here, but please don't hesitate to ask more questions if you need more help :)

**Comment by benlieb** [comment]
Wow, you are so right! There was a debug line in my config files. 

Crazy that that got into the browser. But now knowing that I can give myself some diagnostics lol!
