### ISSUE TITLE
[Feature] Spawn a terminal to edit the text instead of inline like Tridactyl

### ISSUE THREAD

**Issue by Marin-Kitagawa** [glacambre/firenvim#1559]
Tridactyl's feature of spawning a terminal for editing purposes is really useful. At least provide this as an option. This is because, I use my own themes and configurations (mostly in Lua). This is not rendered properly inline and sometimes the error message box from `Astronvim` is too big that it hides the entire text being typed. Also, sometimes the `textarea` is too narrow. So, it will be better to spawn a terminal that provides flexibility for editing and a broader viewport.

**Comment by glacambre** [comment]
For spawning Neovim in a true terminal/GUI, I would recommend using [GhostText](https://github.com/fregante/GhostText). I think I would not be able to do anything better enough to justify duplicating efforts/extensions.

If the Firenvim window is too small, you can make it bigger with `:set lines=20 columns=200`. You can also [configure Firenvim to use Neovim's commandline](https://github.com/glacambre/firenvim#choosing-a-command-line) instead of the default "floating" command line, this might help too.

I would also be interested in a screenshot of what isn't rendered properly and a description of how it should be rendered instead, I'm all for fixing bugs :)

**Comment by Marin-Kitagawa** [comment]
Oh thanks a lot. I am right now writing this using `GhostText`. Also, thanks for the command. Will try
