### ISSUE TITLE
using in note-taking App

### ISSUE THREAD

**Issue by lbgws2** [glacambre/firenvim#1585]
I would like to use firenvim in Notion or Evernote

So that I can write anytime, anywhere

Notion, evernote limits each line of content to a DIV

Is there a way to load all the content

Or other note taking apps can achieve this

**Comment by glacambre** [comment]
>Is there a way to read all the content

Possibly. Have you tried [changing what element Firenvim should use](https://github.com/glacambre/firenvim?tab=readme-ov-file#configuring-what-elements-firenvim-should-appear-on) ? I can't give you exact instructions because Notion and Evernote are proprietary applications that require an account.

>Or other note taking apps can achieve this

Have you tried using a regular neovim + [syncthing](https://github.com/syncthing/syncthing) to synchronize your notes across devices?

**Comment by lbgws2** [comment]
@glacambre 

i'm using neovim and syncthing synchronize  notes now

I'm just looking for a possibility

**Comment by dwolf42** [comment]
> > Is there a way to read all the content
> 
> Possibly. Have you tried [changing what element Firenvim should use](https://github.com/glacambre/firenvim?tab=readme-ov-file#configuring-what-elements-firenvim-should-appear-on) ? I can't give you exact instructions because Notion and Evernote are proprietary applications that require an account.
> 
> > Or other note taking apps can achieve this
> 
> Have you tried using a regular neovim + [syncthing](https://github.com/syncthing/syncthing) to synchronize your notes across devices?

Would you mind explaining this process a bit more? I'm new to Firenvim and I can not figure out where to do these changes, so I could get Firenvim running on Evernote.
Cheers!

**Comment by glacambre** [comment]
@dwolf42 I can't unfortunately. You need to figure out what HTML element Firenvim should take over - I can't give you any pointers because I don't use evernote. It's truly a guessing game, there is no heuristic you can go by in order to figure this out.

Once you've chosen an element, you need to find a uniquely-identifying CSS selector for it (again, no way for me to tell you how to do this - selectors can change across page reloads) and tell firenvim to use it as described [here](https://github.com/glacambre/firenvim?tab=readme-ov-file#configuring-what-elements-firenvim-should-appear-on).

**Comment by dwolf42** [comment]
@glacambre My bad, I'm sorry! I meant how, or where, do I have to alter Firenvim? I'm aware of your link, but I seem to be unable to figure out where to make those changes.

**Comment by glacambre** [comment]
@dwolf42 Firenvim configuration options should go in your init.lua :)

**Comment by dwolf42** [comment]
@glacambre Thank you very much!

**Comment by dwolf42** [comment]
@glacambre Thanks to your very kind help and those of the Evernote forums user mackid1993, I was able to write this script here:

vim.g.firenvim_config = {
    localSettings ={
        ['https://www.evernote.com/'] = { 
            selector = "en-note",
            takeover = "always"
        }
    }
}

Maybe this is also of help for @lbgws2 in case they haven't figured it out on their own anyway.

**Comment by glacambre** [comment]
Thank you for sharing your solution! :)
I think this indeed answer's @lbgws2's query, so I'll close this issue, but don't hesitate to ask more questions if you still have some.
