### ISSUE TITLE
Optionally do not use for input fields.

### ISSUE THREAD

**Issue by mcepl** [glacambre/firenvim#17]
So, with the latest release, we have it finally working in my Firefox. Thank you!

I like this extension very much, but even I have to admit that using it for input fields seems like a bit too much. Could we get an configuration (compile-time even) option to use it for textareas only?

Thank you.

**Comment by glacambre** [comment]
Thank you for your kind words :).

This is definitively planned and I want it to be a runtime option (I want to be able to disable firenvim on specific websites, specific inputs and so on).

**Comment by glacambre** [comment]
Closed in 77417f998b5ffbcffbde5e83ef9b33992478f951 .

In order to choose what elements Firenvim should work on, update to 0.1.6, go to about:addons, click on "preferences" (or "options" if you're on windows) and change the content of the area under the `Elements where Firenvim should be used`.
I am not very satisfied with the help description I wrote, if you're having trouble understanding how this setting works or if you have a better way to describe it, please let me know :).

**Comment by mcepl** [comment]
Hmm, when trying
```
.*reddit\.com div.DraftEditor-root span[data-text="true"]
```
I don't get firenvim activated when I want to add a new comment to the reddit page (e.g., https://is.gd/zXOzIA). And should the RegExp be ``reddit.com`` or ``.*reddit.com``?

**Comment by glacambre** [comment]
Both RegExps should work. The reason the reddit editor doesn't work is that it's a contenteditable element (#8), which requires extra work in order to update.
Clicking the `switch to markdown` button should insert a regular textarea in the page that Firenvim can work with.
