### ISSUE TITLE
Vim airline NerdFont icons not working

### ISSUE THREAD

**Issue by blasco** [glacambre/firenvim#185]
In my terminal they are working fine, but in firenvim the vim-airline icons do not display. Is it possible to make them work? Also the font looks really small, is this a normal issue? I'm trying to fix it with the autostart function:
```
autocmd UIEnter * call OnUIEnter(deepcopy(v:event))
```
and there trying to adjust the font. Is there a better approach?

**Comment by alerque** [comment]
See issue #110 for how to set the font an size.

**Comment by glacambre** [comment]
Yep, as alerque pointed out, #110 has instructions for setting fonts and font size. Please note that for firenvim, `guifont` requires you to write the name of the font as you would write it when specifying a `font-family` rule in CSS. I think an easy way to experiment with that is to open the webdev console (`<CS-I>` in both firefox and chrome) and use the tools that let you edit stylesheets to try to find the right name.

I'm not sure if NerdFont will work. Doesn't it use weird font hacks in order to be able to cram icons in a font? Do these hacks in browsers?

**Comment by alerque** [comment]
By the way, the Nerd patched fonts work fine for me. You can see how [I have them setup here](https://github.com/alerque/que-vim/blob/master/.config/nvim/init.vim#L908):

```vim
set guifont=Hack\ Nerd\ Font
```

Note you can tack on `:h10` or whatever size you want to the end of this line to force a font size.

**Comment by blasco** [comment]
That's weird. I also have them like that, and they do work in my terminal, but not in the browser.

**Comment by blasco** [comment]
This is how it looks in mine: 

![Uploading Screenshot_2019-10-29_11-14-47.png…]()

**Comment by alerque** [comment]
This is how it looks in mine. Normally I actually have Airline and the various bars disabled, but I turned them off there to show that they work. Note this is *Hack Nerd Font* with mostly Powerline symbols, but one or two things coming from Nerd...

![image](https://user-images.githubusercontent.com/173595/67758683-33354400-fa4f-11e9-9a4c-4bdbc56435ac.png)

**Comment by glacambre** [comment]
@blasco Did you try to set the font "manually" through the dev tools? To do that, you have to open the dev tools (`<CS-I>`), open a firenvim frame and use the element inspector in order to select an element with the neovim frame. This should show you a list of CSS attributes that apply to the selected element in the rightmost column. Among them, you should find this rule:
```css
* {
        font-family: monospace;
}
```
Try to change monospace to another value (e.g. `Inconsolata Nerd Font Mono`). If it works and the powerline symbols are displayed correctly, this is a bug in firenvim. I'd be grateful if you could run `:set guifont=Inconsolata\ Nerd\ Font\ Mono` in the firenvim frame and then give us the content of the `<style>` element the id of which is `nvim_guifont`.
If manually changing the font doesn't work, this is most likely an issue with your browser/font configuration and I have no idea how to fix this :).

@alerque Is your airline rendered exactly as it is in your terminal? It looks quite different from blasco's.

**Comment by alerque** [comment]
@glacambre Yes it is, but my airline is heavily customized. Several display issues are evident but those have to do with the color scheme I was in the middle of messing with so the segments don't transition like powerline is supposed to. @blasco's capture shows some customization too actually.

**Comment by masaeedu** [comment]
Is what's going on here that we don't have font fallthrough working? The font I'm using doesn't have all the glyphs I need to make powerline etc. work, but in normal gvim it seems like there's some kind of font fallthrouhg that happens so that even if I set `set guifont=curie\ Medium\ 10`, the missing glyphs are picked from a different font.

I can try to patch it with the Nerd Fonts stuff, but it'd be nice if it worked the same way as GUI vim.

**Comment by glacambre** [comment]
I think you can customize font fallback with fontconfig on linux. You could also specify multiple fonts with `:set guifont=FirstFont,\ SecondFont,\ ThirdFont` but this will prevent you from specifying a font size.

**Comment by masaeedu** [comment]
@glacambre If it is indeed font fallback that makes it work, I think it's set up correctly on my system, because the NerdFonts icons show up just fine in my actual terminal (Konsole). It's only in the browser that the characters are missing.

**Comment by glacambre** [comment]
Does nerfont fallback work on regular webpages (you can test that by copy/pasting your airline characters into an HTML document, setting the font with CSS and then opening the document in your browser)?

**Comment by masaeedu** [comment]
@glacambre Nope, doesn't look like that works. I tried just copy pasting the Haskell icon into your comment, which produces:

![image](https://user-images.githubusercontent.com/3674056/71376499-b9719080-258f-11ea-92a8-a29d7808cabf.png)

Everything works if I use a patched "xyz Nerd Font" version of a font (e.g. "Hack Nerd Font").

![image](https://user-images.githubusercontent.com/3674056/71376566-e4f47b00-258f-11ea-8089-9a81420f8ef3.png)

It's only when using an unpatched font that relies on font fallback that things stop working. I guess I need to figure out why that's not working in my browser.

**Comment by glacambre** [comment]
Ok, I'm going to close this issue then as I believe there's nothing I can do. If it turns out that I'm wrong, please let me know, I'll reopen it.

Thanks for reporting back! :)
