### ISSUE TITLE
Problem with gerrit.

### ISSUE THREAD

**Issue by damani42** [glacambre/firenvim#220]
OS Version: Fedora 30
Browser Version: 69.0
What I tried to do: Make code review on gerrit
What I expected: Doesn't run neovim gerrit for review field

For example on this page:

https://review.opendev.org/#/c/692681/1/test-requirements.txt

Neovim run on the right field so I lost context review. When i quit neovim the diff disappear.

**Comment by glacambre** [comment]
I recommend you use firenvim's [configuration mechanism](https://github.com/glacambre/firenvim#configuring-the-browser-addon-behavior) to prevent it from automatically spawning neovim instanes on review.opendev.org:
```
let g:firenvim_config = {
    \ 'localSettings': {
        \ '.*': {
            \ 'selector': 'textarea',
            \ 'priority': 0,
        \ },
        \ 'review.opendev.org': {
            \ 'selector': '',
            \ 'priority': 1,
        \ }
    \ }
\ }
```

I'll close this issue because I believe this solves your problem but feel free to reopen/let me know if you need more help.
