### ISSUE TITLE
Firenvim lagging like crazy when scrolling through "bigger" scripts

### ISSUE THREAD

**Issue by JonatanSiden** [glacambre/firenvim#250]
Hi,

For some reason when there's more than 1 "page" that fits the screen in firenvim - scrolling up or down is causing HUGE freeze lags, almost like the browser crashes.

Is this a known issue? why is this suddenly happening?

Cheers!

Best,

J

**Comment by glacambre** [comment]
When you open an issue, please fill in the information about what browser you're using - this saves time because I don't have to check both browsers I support and wonder if I'm correctly reproducing your issue.

I changed the scrolling algorithm in v0.1.14 (the previous one wasn't correct). It looks like Chrome can't optimize the new one when scrolling down (while firefox can), so I'll need to investigate.

**Comment by glacambre** [comment]
I fixed your issue in #260. I'll publish a new release tomorrow and given how slow the chrome store is, you'll probably get the fix by the middle of the week.

Thanks for reporting this issue :)
