### ISSUE TITLE
Start insert mode after last character of the buffer automatically

### ISSUE THREAD

**Issue by mimame** [glacambre/firenvim#257]
- OS Version:Linux 5.3.11-1-MANJARO
- Browser Version: 71.0b9 (Firefox Developer Version)
- Browser Addon Version: 1.14
- Neovim Plugin Version: master
- What I tried to do: Move the cursor position to the last line and character position and start the insert mode automatically
- What happened: normal! G and startinsert! are not working insiide the onUIEnter function
I've tried from inside the [OnUIEnter](https://github.com/mimame/.dotfiles/blob/master/vim/.vimrc#L1356) function  with:
```
normal! G
startinsert!
```
and several other similar tries but neither startinsert! goes to the last position of the line
I didn't try in https://github.com/glacambre/firenvim/blob/master/autoload/firenvim.vim#L190 with +$ +starti!

Thanks so much in advance

**Comment by glacambre** [comment]
You can use
```
function! s:IsFirenvimActive(event) abort
  if !exists('*nvim_get_chan_info')
    return 0
  endif
  let l:ui = nvim_get_chan_info(a:event.chan)
  return has_key(l:ui, 'client') && has_key(l:ui.client, "name") &&
      \ l:ui.client.name is# "Firenvim"
endfunction

function! OnUIEnter(event) abort
  if s:IsFirenvimActive(a:event)
    au BufReadPost *.txt ++once call timer_start(100, {_ -> feedkeys("GA")})
  endif
endfunction
autocmd UIEnter * call OnUIEnter(deepcopy(v:event))
```
The BufReadPost command is needed because the OnUIEnter event is triggered before any buffer is created. The `timer_start` is needed because firenvim first opens the file and only after that copies the content of the page into the buffer. Moreover, firenvim will move the cursor to where you clicked on the textarea after filling the buffer.

I am not very satisfied with the need to use `timer_start` so I'll try to find a better way to do what you want to do.

**Comment by mimame** [comment]
Thanks so much!
It's working perfectly
