### ISSUE TITLE
List of websites where firenvim shouldn't be enabled by default

### ISSUE THREAD

**Issue by glacambre** [glacambre/firenvim#264]
#247 made firenvim a bit too aggressive, it now pops up on riot and slack by default, which is annoying.
```
let g:firenvim_config = {
    \ 'localSettings': {
        \ 'riot.im': {
            \ 'selector': '',
        \ },
        \ 'slack.com': {
            \ 'selector': '',
        \ }
    \ }
\ }
```
Is enough to disable it there but it should probably be a default.

**Comment by alerque** [comment]
It might be worth having `add()`/`remove()` functions so that a default array can be maintained in the plugin and config files can just tweak to users' preferences. Having users set the entire array in their rc files for something that potentially has a lot of values is starting to get messy. Per-site configs could also be shared easier if each one was self contained.

Just brainstorming here, but maybe an adder that that accepted a site, selector, and optional priority arguments, and a remover that just took the site...

```vim
call firenvim#add_site_config('riot.im', '<selector>')
```

**Comment by glacambre** [comment]
Actually firenvim shouldn't be disabled by default on slack/riot. Instead it should become good enough to be used even in the context of a chat app. A mapping like `inoremap <CR> <Esc>:w<CR>ggdGa` is a third of the solution (it shouldn't be a default - just documented somewhere) - we also need a way to send `<CR>` to the underlying element to make it understand it should send messages and #168 to avoid wasting precious space.

**Comment by alerque** [comment]
I've been using Firenvim even in the context of chat (Mattermost, Gitter, and Stack Exchange) and it does work, but with the caveats you mention. It requires at least about 3 lines of space because the command bar takes up 1+, and sending messages requires too much song and dance. A way to map a single key to save, close, and send the message, then open again would be AWESOME! Combined with a fix for [the over aggressive reopening](https://github.com/glacambre/firenvim/issues/265#issuecomment-559069901) that will make it easier to drop back to the native editor for things like auto completion, and the world starts to get rosy(er).

**Comment by NilsIrl** [comment]
I wouldn't disable slack by default. It does work to an extent and disabling it by default will just make it more confusing.

**Comment by glacambre** [comment]
#271 #292 and #360 implemented everything I need to use Firenvim comfortably on `riot.im` so I'll close this issue.
