### ISSUE TITLE
Feature request: Takeover='nonempty'

### ISSUE THREAD

**Issue by BlueDrink9** [glacambre/firenvim#286]
I would like to request the option to set `takeover : nonempty`, or similar, to only take over inputs that already have text in them.

My biggest pain-points with firenvim at the moment is it taking over tiny text boxes for things like search boxes, or chat boxes.

Usually, these things start off empty. On the other hand, vim excels not at writing text, but editing it. Therefore it is more useful to me if there is already text in the box I select, and I can bring vim to bear to edit it.

On those occasions where I want to edit empty boxes, I can either set a rule for it or manually trigger it with a shortcut.

**Comment by glacambre** [comment]
If what's annoying you is that firenvim appears on websites with chat apps, wouldn't it make more sense to [disable firenvim on said sites](https://github.com/glacambre/firenvim#configuring-what-sites-firenvim-should-automatically-appear-on)? After all you might start typing a message, focus another element in the page and then come back to the input field you're editing, which would make a `takeover: nonempty` firenvim appear again.

**Comment by BlueDrink9** [comment]
`if exists("#airline")`

  Thank you

**Comment by BlueDrink9** [comment]
I could, but I would have to do that for every new chat site, which might end up with quite a sizable file for configuring it.

I'm sure there are other examples for this feature as well, especially given vim's benefits as an editor rather than a writer.

If I focus away and then back, it probably wasn't a quick message, so I won't be as annoyed about having to `i<esc>:wq<return>` to send it. Happy for that trade-off.

If it's a difficult feature to implement, I understand. I do believe this would be the ideal solution for me though.

**Comment by glacambre** [comment]
It would be quite a trivial change, but I want to avoid implementing features that do not make sense/aren't the optimal solution to a problem (even easy ones!). That's why I want to explore the space of possible solutions with you before actually implementing anything :).

Why is having a large configuration file something you want to avoid? If firenvim's conf file gets too big you can stick it in another file and source it. Is the problem actually that adding websites to your `g:firenvim_config` requires too much effort? Would having a button/command that lets you automatically add websites to it better? Is it that editing one big object is annoying - would #269 help here?

#248 also mentionned being annoyed by firenvim taking over small textareas - would the original idea of specifying a minimal input height help?

Feel free to answer no to all might questions :).

**Comment by BlueDrink9** [comment]
It's already a separate file. The size itself isn't the main problem... but really the hassle of having to add new ones, when there is a possibility of configuring 'smarter'
behavior.

I'm definitely keen to see #269 implemented, it will be much more elegant. I'd be interested in seeing whether it affected startup speed for large numbers of sites.

#248 would help, but there are some sites where the input box is small but
grows with the post size - facebook, SE comments, even github, and there are
chat sites where the input box is relatively large by comparison.

So far I still think there's reason for this extra option, again going back to the idea that I often mainly want to use nvim for editing existing text rather than writing new
text.

**Comment by glacambre** [comment]
I'll publish a new release containing ff6bd80 next week :)

**Comment by BlueDrink9** [comment]
Thank you!
