### ISSUE TITLE
Thunderbird support

### ISSUE THREAD

**Issue by glacambre** [glacambre/firenvim#314]
Thunderbird kind of supports webextensions:

https://thunderbird-webextensions.readthedocs.io/en/68/

**Comment by glacambre** [comment]
According to @kewisch on Matrix here's no way to run a {web,mail}extension script in a compose window yet.

**Comment by Qeole** [comment]
Hi, the [`composeScripts` API](https://thunderbird-webextensions.readthedocs.io/en/78/composeScripts.html) was added to Thunderbird 77, and should now allow one to run content scripts in compose windows? (I'd _love_ using neovim in Thunderbird!)

**Comment by glacambre** [comment]
@Qeole Thanks for notifying me, I hadn't noticed :).

**Comment by glacambre** [comment]
In about an hour and a half of work, I almost have something that works! I must say that I'm quite proud of some of the parts of Firenvim's architecture that enable this. A shame I also had to discover a few disgusting ones along the way :smile: 

![20201103_20h13m01s_grim](https://user-images.githubusercontent.com/11534587/98030523-715b0580-1e11-11eb-9a96-dd428c03891f.png)

**Comment by Qeole** [comment]
Impressive, and exciting!

**Comment by glacambre** [comment]
Firenvim now works in Thunderbird! You can download it here: https://addons.thunderbird.net/en-US/thunderbird/addon/firenvim/

Note that it currently requires Thunderbird Nightly **and** patching Thunderbird with the patch available here: https://bugzilla.mozilla.org/show_bug.cgi?id=1675589

Hopefully it'll get merged soon (although I wouldn't hold my breath…).

**Comment by Qeole** [comment]
Thanks a lot for this work! I compiled Thunderbird and tried the add-on, and it works well. Here is some feedback on a few issues I noticed:

- The add-on is slow indeed, but I see you have work in progress for a new renderer, sounds great!
- I had troubles to focus on the composition area (in Thunderbird's composing window) and to enter insertion mode. When pressing `i` this would write to the `To:` field, even if I had clicked to the message body area. I had to somehow navigate with multiple hits on `tab` to reach the area. Is this something you experienced too, or is it just me?
- The `ctrl+e` shortcut was ineffective to bring back the Neovim window after I closed it once. But I suppose this is kind of expected, given that Thunderbird lists no shortcut for the add-on.
- I have `'takeover': 'never'` in my nvim init file, but this is not taken into account for Thunderbird and the Neovim window is always launched when starting a new message. Which is a good thing I guess, since `ctrl+e` doesn't work and I don't see how I would open Neovim otherwise :).

Would you like me to open separate issues to track those?

On the bright side, writing emails with Neovim works well, I didn't experience any issue while writing. I can now easily format text, use my shortcuts or run bash commands for writing my messages and this is neat, thanks again for the Thunderbird add-on!
