### ISSUE TITLE
Firenvim instance doesn't follow text area

### ISSUE THREAD

**Issue by NilsIrl** [glacambre/firenvim#320]
Video demo: https://peertube.co.uk/videos/watch/1962c72b-353e-4bf3-b117-10394ce97f3b

**Comment by alerque** [comment]
Thanks for reporting this. I've seen the issue many times but never bothered to report it. It happens pretty much any time the page content shifts and either moves or reshapes the text area. It can also be affected by the overall browser window size changing causing reflows.

**Comment by glacambre** [comment]
As far as I can tell, this isn't an issue that can be solved as there are no JS APIs to detect when an element is moved. There are two potential solutions that don't quite work:
- Polling for the element's position. Polling in the browser is bad for performance and battery life.
- Appending the `<span>` element the neovim iframe lives in right after the textarea and using `position: relative` in order to move the iframe over the textarea. Unfortunately, lots of (badly written) websites rely on things like `.nextSibling` or `selector:nth()` for their features and adding a span right after the textarea would break them.

**Comment by alerque** [comment]
Wouldn't an `onResize` event attached to the overall page canvas detect a lot of these cases? I.e. when content gets stuffed into the page moving the textarea down the overall page canvas will get longer in most cases. This would also catch browser resizes. Or am I missing something?

**Comment by glacambre** [comment]
I already have resize listeners [for the page](https://github.com/glacambre/firenvim/blob/f47791f01a215b6722d426d0cf697b96e383d5d9/src/content.ts#L78-L95) and [for the window](https://github.com/glacambre/firenvim/blob/f47791f01a215b6722d426d0cf697b96e383d5d9/src/content.ts#L227) (the window one is supposed to catch browser resizes and it works for me, I'm surprised it doesn't for you). I hadn't thought about adding a listener on the document element itself though, I'm slightly worried about performance but I believe it's worth trying anyway. Thanks for the suggestion :)

**Comment by alerque** [comment]
It looks like the browser resize _is_ working for me except on sites that muck around with their own layout in response to resize events themselves. Many of those sites break because they move stuff around on the canvas after Firenvim thought it adjusted itself.

**Comment by glacambre** [comment]
Fixed in #331 - it'll reach you when I publish a new release, either tomorrow or the week after. Thank you for reporting this bug and thanks @alerque for finding a good solution! :)
