### ISSUE TITLE
Doesn't work on JIRA comments

### ISSUE THREAD

**Issue by ayellapragada** [glacambre/firenvim#323]
This doesn't seem to work on JIRA comments specifically.
And might be hard for you to access if you don't have currently already use JIRA. 
I'm not familiar with lua, but if you don't have access I can try and poke around and maybe with your help or context I can figure out the issue.

Steps to reproduce:
1. Go to a JIRA ticket
2. Make a new comment, type out anything.
3. Use `:x` to place the text into the comment box.

Expected:
Places text into box as usual.

Actual:
Page does a very quick refresh and nothing is placed into the box.

- OS Version: mac x86-64
- Browser Version: Google Inc. Chrome 79.0.3945.88
- Browser Addon Version: 0.1.17
- Neovim Plugin Version: 0.1.17
- What I tried to do:
- What happened:

**Comment by glacambre** [comment]
Yeah, I don't have access to a JIRA instance :/.

This probably happens because JIRA uses a fancy editor instead of a simple textarea. From reading their [docs](https://confluence.atlassian.com/adminjiraserver072/rich-text-editing-838542372.html), it looks like there's a way to get a simple text editor rather than a rich text editor, could you try that?

If that doesn't work, you will need to implement Jira support yourself. From looking at their docs, they seem to be using something named [tinymce](https://developer.atlassian.com/server/jira/platform/extending-the-rich-text-editor-in-jira/#implementing-toolbar-action) (however I can't get Firenvim to appear on their [demo](https://www.tiny.cloud/docs/demo/full-featured/) so I assume they've modified it).

In order to detect TinyMCE, you will need to write [a function that takes an element and detects if it belongs to a TinyMCE element](https://github.com/glacambre/firenvim/blob/cddf1b14eeabce735ef1646c6f2030f0cf28773b/src/utils/utils.ts#L12-L55). If the element is not in a TinyMCE element, it should return the element itself. If the element is in a TinyMCE element, the TinyMCE element should be returned instead. This function should be added to the [getEditorElement](https://github.com/glacambre/firenvim/blob/cddf1b14eeabce735ef1646c6f2030f0cf28773b/src/utils/utils.ts#L57-L59) function.

Once you've done that, you will need to update the [_getElementContent](https://github.com/glacambre/firenvim/blob/cddf1b14eeabce735ef1646c6f2030f0cf28773b/src/page/functions.ts#L38-L61) function to have it return the TinyMCE element's content (TineMCE's [getContent](https://www.tiny.cloud/docs/api/tinymce/tinymce.editor/#getcontent) function is probably what you will need to use) .

The last step will be to update the [setElementContent](https://github.com/glacambre/firenvim/blob/master/src/page/functions.ts#L179-L211) function to have it set the TinyMCE's element content (probably using [setContent](https://www.tiny.cloud/docs/api/tinymce/tinymce.editor/#setcontent)).

If I'm mistaken and Jira uses something else than TinyMCE, the steps will be roughly the same - discover what text editor jira is using, add a way to detect it to firenvim, add an adaptater to get and set its content.

You can find out how to build Firenvim from source [here](https://github.com/glacambre/firenvim#from-source).

Feel free to ask any question you may have, I'll be happy to answer them :)

**Comment by ayellapragada** [comment]
Wonderful, thanks! I'll look into this and see what I can do. 

Feel free to close this or potentially add it to your readme as a list of currently known unsupported sites?

Not really sure what you'd prefer, but your call either way.

**Comment by brownjohnf** [comment]
FWIW, this seems to work just fine on Jira for me. I'm on the cloud
Jira, which might be a different version. That's with default settings
with the text editor enabled.

The text doesn't always come out _looking_ correctly afterwards, but
that's just because the real-time Jira editor isn't processing the
characters as typed.

**Comment by pmilosev** [comment]
I have access to both Atlasian products, Jira and Confluence - both use `tinymce`.
As I spend a lot of time editing Confluence pages, I can invest some time trying to implement some support for it. I have a solid development experience, but no web development or lua, so some pointers would help.

First issue would be to get the selectors right. I have tried to match the `body` using selectors `#tinymce` and `body[data-id=wysiwygTextarea]` but I can't get `firenvim` iframe to appear - I guess because the `body` element never gets focus, but actually some of the inner element.

Here is what the HTML looks like for few dummy paragraphs:
```html
<body id="tinymce" class="mce-content-body aui-theme-default mceContentBody wiki-content fullsize notranslate" data-id="wysiwygTextarea" style="padding-top: 118px; height: auto" data-title="Playground" contenteditable="true">
<p>kjhkjhkjh<span data-mce-type="bookmark" id="mce_2_start" style="line-height: 0px"></span><br data-mce-bogus="1"></p>
<p>sdfdfg<br data-mce-bogus="1"></p>
<p>dfgdfg<br data-mce-bogus="1"></p>
<p>dfg<br data-mce-bogus="1"></p>
<div data-mce-bogus="true" class="synchrony-container synchrony-exclude" style="user-select: none;" contenteditable="false"><div data-mce-bogus="true" contenteditable="false"></div></div></body>
```
<img width="1160" alt="Screen Shot 2020-11-23 at 13 11 56" src="https://user-images.githubusercontent.com/288658/99960764-92b66e00-2d8d-11eb-9738-7037af08067a.png">

I've also tried selecting the individual `<p>` elements for each paragraph, but again failed to get firenvim iframe. 
Ideally the support should focus the main `body` and filter out all the HTML tags, such that you would edit the text as you would within the WYSIWYG editor. Jira / Confluence editor will than add the HTML stuff when the text is published.

**Comment by glacambre** [comment]
@pmilosev Thanks a lot for taking the time to improve Firenvim! Build instructions are available [here](https://github.com/glacambre/firenvim#from-source).

Once Firenvim is built and loaded in your browser, we need to find out if Firenvim is listening for focus events on the element we care about (`#tinymce` in the context of this page although I think relying on `.mce-content-body` or `.mceContentBody` might be more robust).

To do this, I would suggest either adding a `console.log` call or a breakpoint in the `nvimify` function:

https://github.com/glacambre/firenvim/blob/e57643b33f8b8d2a42b3d1d3c667c3146306a341/src/common.ts#L32

Then, try to trigger Firenvim by clicking on the tinymce element. Then there are multiple situations:
- The breakpoint/console.log isn't reached:
  * Possibly because an inner element received the focus event and prevented it from bubbling up.
    + We can check this by inputing `document.activeElement` in the dev console.
    + We can also try adding event listeners: right click on the element you think might be getting the event, copy its unique selector, move to the console, run `document.querySelector("THE_SELECTOR").addEventListener("focus", console.log)`, then focus the tinymce element again.
  * Or the tinymce element didn't get a focus listener. This can be checked by adding a console.log call or a breakpoint in [setupListeners](https://github.com/glacambre/firenvim/blob/e57643b33f8b8d2a42b3d1d3c667c3146306a341/src/content.ts#L98) to check if the tinymce element is among the selected elements.
- The breakpoint is reached but somehow the firenvim frame doesn't popup:
  * This could be because something makes it leave early.
    + This can be checked by adding more console.logs/breakpoints everywhere in `nvimify`. If control flow leaves the function before [firenvim.attachToPage](https://github.com/glacambre/firenvim/blob/e57643b33f8b8d2a42b3d1d3c667c3146306a341/src/common.ts#L95) is reached then there is definitely something wrong.
  * This could be because an error happened while trying to fetch information from the page. Adding breakpoints/console.logs to the [editor](https://github.com/glacambre/firenvim/blob/master/src/editors/editors.ts) [functions](https://github.com/glacambre/firenvim/blob/master/src/editors/TextareaEditor.ts) would help us let us know what might be wrong.

The code can be very confusing and I've tried to make my instructions terse so please don't hesitate to ask more questions, I'll be delighted to help you get firenvim working on JIRA :)

**Comment by pmilosev** [comment]
@glacambre

Sorry for the late reply, I was setting up a new computer and needed to get few things into place.
I plan to give this issue some attention this weekend.

Currently I have a working build and run environment. I'm able to build the project acoording to your instructions and I'm able to load the plugin in Firefox Developer Eddition (due to permission issues with regular Firefox release).

I tried adding a simple console.log in `common.ts` as you suggested, but I can't see any output neither in Firefox debugger console nor `firenvim` script output. I suspect `common.ts` should be part of the plugin running within Firefox but I don't see it in the Debugger.

![Screen Shot 2020-12-04 at 12 54 04](https://user-images.githubusercontent.com/288658/101161029-3f1b0e80-3630-11eb-9b46-28bd6a69a09e.jpg)

Can you please help me orient myself which parts are running within the browser plugin, which run as background process and how to debug each part.

Thanks

**Comment by glacambre** [comment]
@pmilosev Ouch, I think the issue is that the build instructions are pointing to the sr.ht mirror instead of github and it's a bit behind. Could you try running the following commands to update your repo?

```
git remote remove origin
git remote add origin https://github.com/glacambre/firenvim
git fetch origin master
git rebase origin/master
```

After that, re-building firenvim and reloading it in the browser should make `common.ts` appear. Sorry about this!

**Comment by pmilosev** [comment]
I actually ignored the first step in the build instructions as I already had the github repo forked and cloned
``` bash
firenvim on ? master [!] ? git remote show origin
* remote origin
  Fetch URL: https://github.com/pmilosev/firenvim.git
  Push  URL: https://github.com/pmilosev/firenvim.git
  HEAD branch: master
  Remote branches:
    draftjs       tracked
    master        tracked
    webgl_rewrite tracked
  Local branch configured for 'git pull':
    master merges with remote master
  Local ref configured for 'git push':
    master pushes to master (up to date)
```

Anyway I cloned directly `https://github.com/glacambre/firenvim` in a new directory and I still have the same issue.

**Comment by pmilosev** [comment]
What timezone are you in ?
If you have an hour to spend or something we can maybe organize a call to get things going quicker ?

**Comment by pmilosev** [comment]
OK I figured it out.
The debugger shows only the scripts which are currently loaded.
So instaed of going `about:debugging` in new tab I had to `F12` in a tab where I have the page with the text area.

**Comment by pmilosev** [comment]
Status update:
I can't define a selector that would trigger `nvimify`.
I suspect this to be due to Confluence / Jira editor elements are actually within an `iframe`.
From Firefox debugger in order to select the element I need to run:
```javascript
document.querySelector("#wysiwygTextarea_ifr").contentWindow.document.querySelector("#tinymce")
```

If I'm not mistaken `firenvim` is triggered by setting proper event listeners to all elements matching the defined selector:
```javascript
        // This mutation observer is triggered every time an element is
        // added/removed from the page. When this happens, try to apply
        // listeners again, in case a new textarea/input field has been added.
        const toPossiblyNvimify = Array.from(document.querySelectorAll(selector));
        toPossiblyNvimify.forEach(elem => addNvimListener(elem));
```

However `querySelectorAll()` will not return the elements from the `iframe`.
Next I'll try to modify the lines above such that if the current element is an iframe, instead of registering a listener, to actually get all inner elements from that document and register listeners.

**Comment by glacambre** [comment]
AFAIU, Firenvim is injected in [every frame](https://github.com/glacambre/firenvim/blob/776e3d4903f722715c059e19c217940c018505a3/src/manifest.json#L38), so it shouldn't have issues working with elements hidden within iframes (I even wrote a [test](https://github.com/glacambre/firenvim/blob/776e3d4903f722715c059e19c217940c018505a3/tests/_common.ts#L721) for that). You can verify this by loading [parentframe.html](https://github.com/glacambre/firenvim/blob/master/tests/pages/parentframe.html) in your browser and seeing if Firenvim works.

Jira elements being hidden in an iframe will make debugging much more annoying. Does loading the url of this iframe in a newtab work? If it does, I'd recommend using that to debug firenvim.

>If you have an hour to spend or something we can maybe organize a call to get things going quicker ?

I'm on GMT+1, I should be available tomorrow afternoon and sunday all day. There's a [firenvim room](https://app.element.io/#/room/#firenvim:matrix.org) on matrix if you want to discuss things live :)

**Comment by pmilosev** [comment]
Sorry I have written an update but forgot to post it - yes iframes are not an issue, firenvim is injected properly.
I'm trying to figure out the debugger yet.

Next issue that I need to resolve is proper element selection.
I'm able to trriger `nvimify` when I set the selector to be '*', but not when I select for concrete elements like the main `<body>` or the `<p>` tags inside.

Due to the rich editor the `iframe` will probably contain nested elements, so I expect to be hard to focus on the right element. Perhaps we should register matching elements to react on the capture phase of the event such that the `#tinymce` body tag can intercept and react on focus event of any inner element:
https://stackoverflow.com/questions/38861601/how-to-only-trigger-parent-click-event-when-a-child-is-clicked

I'm also on GMT+1 - I'll check the matrix room.

**Comment by pmilosev** [comment]
This issue will become relevant: https://github.com/glacambre/firenvim/issues/812

**Comment by glacambre** [comment]
Hi everyone. I published a new release that might help Firenvim work with JIRA, let me know if you see an improvement :).

**Comment by pmilosev** [comment]
@glacambre I tested shortly today with v.0.2.4.
The editor frame seems to show consistently as expected.

I will spend some time to see if I can come up with a useful editor.

**Comment by pmilosev** [comment]
I have a simple editor that works.
Combined with some vim plugins to re-format the (otherwise compacted) HTML, it's not that bad.
I couldn't push my branch directly to your repo so tomorrow I'll push to my fork and send you a pull request.

Cursor positioning currently does not work.
TinyMCE does not have an API to get cursor position, but I thought adding a bookmark `span` and then restore the cursor by searching for it.
As I don't have much time to debug it, I would like to push the branch as it is.

**Comment by pmilosev** [comment]
Pull request #936

**Comment by glacambre** [comment]
Firenvim now works on JIRA thanks to @pmilosev! In order to use it, you'll have to configure Firenvim like this:
```vim
let g:firenvim_config = {
    \ 'localSettings': {
        \ 'javascript-pattern-matching-the-url-of-the-jira-or-confluence-page': {
            \ 'selector': '#tinymce',
            \ 'content': 'html'
        }
    \ }
\ }
```

Related PRs: https://github.com/glacambre/firenvim/pull/936 and  https://github.com/glacambre/firenvim/pull/937 .

**Comment by pmilosev** [comment]
### Summary
Tinymce editor, which is the editor used in Confluence and JIRA, is now supported by the default `TextareaEditor.ts` in firenvim. I tested with Confluence, JIRA and the https://www.tiny.cloud/ demo - no apparent issues.

### Firenvim config
```vim
let g:firenvim_config = {
    \ 'globalSettings': {
        \ 'alt': 'all',
    \  },
    \ 'localSettings': {
        \ '.*': {
            \ 'cmdline': 'neovim',
            \ 'content': 'html',
            \ 'selector': '#tinymce',
            \ 'takeover': 'never',
        \ },
    \ }
\ }
```
Important parts are the `content` and `selector` parameters.

### Useful vim plugins
TinyMCE content is loaded as HTML. Especially Confluence pages can get quite complicated and the HTML is loaded in a compacted form. Using https://github.com/dense-analysis/ale with https://github.com/prettier/prettier seems to work nice at formatting the HTML to a human-readable form without braking it.
```vim
let g:ale_fixers = ['prettier']
```
![Screen Shot 2021-02-07 at 13 18 14](https://user-images.githubusercontent.com/288658/107146225-00af1200-6947-11eb-939b-a8875cd9beac.jpg)


![Screen Shot 2021-02-07 at 13 16 26](https://user-images.githubusercontent.com/288658/107146183-c5144800-6946-11eb-8d01-2a05ed309361.jpg)

**Comment by pmilosev** [comment]
I came here again just to say THANK YOU to @glacambre one more time :)

I've been using the setup above for few days now, mostly writing Confluence documentation and it works far better than I expected. This is the first time in years that I finally don't suffer writing reports, concepts, policies and other lengthly prose, which actually comprises a good deal of my work.

There are some occasional issues converting from HTML to Markdown to HTML, but that have been exclusively due to TinyMCE / Confluence tables not being proper HTML etc. But the ability to selectively convert parts of the document helps a lot.

Thanks @glacambre!
