### ISSUE TITLE
Field marked as focused when it isn't

### ISSUE THREAD

**Issue by NilsIrl** [glacambre/firenvim#343]
On riot.im, the page steals focus but the firenvim text area still shows up as focused (color).

This happens when writing is done (`:w`)

**Comment by NilsIrl** [comment]
Also just happened on github. (was no able to reproduce though)

**Comment by NilsIrl** [comment]
Please note that the problem isn't that focused is getting stealed but rather that the textarea still shows up as focused.

**Comment by glacambre** [comment]
I believe this is a Firefox bug: the iframe's window isn't getting a `blur` event even though it is actually blurred.

**Comment by glacambre** [comment]
I did consider that Riot managing to grab focus when doing `:w` rather than `:w<CR>:call frenvim#focus_inpu()` was a bug (and a pretty annoying one at that!) so I fixed it in #360. This had the nice side-effect of also sending blur events to the iframe (but you won't notice since it gets automatically refocused right after being unfocused) so this bug is squashed.

Thanks for reporting it! :)
