### ISSUE TITLE
"Press enter to continue" blocks startup

### ISSUE THREAD

**Issue by BlueDrink9** [glacambre/firenvim#350]
- OS Version: linux x86-64 (arch)
- Browser Version: Google Inc. Chrome 79.0.3945.79
- Browser Addon Version: 0.1.17
- Neovim Plugin Version: 0.1.17
- What I tried to do: Debug firenvim by using `echom 'some long startup message 1'`
- What happened: In terminal, `./firenvim` echos the message, and prompts the user to continue.
In browser, firenvim pauses, then closes itself when it sees that it is hanging.

I see you can't parse stderr, but would it be possible to try `feedkeys('<cr>')` or something similar if neovim doesn't respond?

**Comment by BlueDrink9** [comment]
I was sure this had been an issue already, but I couldn't find the old one sorry

**Comment by glacambre** [comment]
You can't use `echom` in your init.vim before Firenvim is loaded because Firefox expects messages written to neovim's stdout to be formatted according to the [NativeMessaging](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_messaging) protocol. Writing random strings to it will result in Firefox ignoring the port+config message Neovim has to send and this is what makes Firenvim hang.

I would recommend appending messages to an array and displaying that array once the UiEnter event has been triggered or using `echoerr` and redirecting errors to a file in the `~/.local/share/firenvim/firenvim` script.

>I was sure this had been an issue already, but I couldn't find the old one sorry

No problem :). You might be thinking of https://github.com/glacambre/firenvim/issues/206#issuecomment-549740115 ?

**Comment by BlueDrink9** [comment]
Ah, thank you. Worth documenting somewhere, maybe in `TROUBLESHOOTING.md`?

**Comment by justinmk** [comment]
> You can't use `echom` in your init.vim before Firenvim is loaded because Firefox expects messages written to Neovim's stdout to be formatted according to the [NativeMessaging](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_messaging) protocol

If `nvim` was started with `--embed` (_without_ `--headless`) then it should not do anything until the UI connects. How is firenvim starting nvim?

**Comment by glacambre** [comment]
I'm using `--headless` because I need to write arbitrary messages to stdout with `stdioopen()`.

**Comment by glacambre** [comment]
Closed in 969837547d71edff0dc997269aa30ba43c5fac90

**Comment by justinmk** [comment]
> Edit: Oh, but it looks like I can use both `--embed` and `--headless`. I'll try that!

Yeah, but `--headless` tells Nvim _not_ to wait for UI to connect (because "headless" implies "no UI"). Normally with `--embed` Nvim waits for the UI, in order to avoid the issue reported here. (see [here](https://github.com/neovim/neovim/wiki/Following-HEAD#20180922) or `:help --embed`)

> I'm using `--headless` because I need to write arbitrary messages to stdout with `stdioopen()`.

Ah right, I forgot. I wonder if `--embed --headless` should wait for `stdioopen()` ? Would that help you?
