### ISSUE TITLE
VimFX compatability

### ISSUE THREAD

**Issue by millysoose** [glacambre/firenvim#352]
It seems firenvim does not get along with the VimFX extension.
VimFX should enter ignore mode when inside a text container. However, when typing inside the firenvim window VimFX stays in normal mode which conflicts with ordinary typing.

This could also be classified as a VimFX issue I suppose.

**Comment by glacambre** [comment]
Funny, this issue sounds a lot like https://github.com/akhodakivskiy/VimFx/issues/532 - one of the first issues I opened with this github account :).

>This could also be classified as a VimFX issue I suppose.

I would even go farther and say that this can only be classified as a VimFX issue since Firenvim works fine when VimFX isn't installed :).

I believe there's nothing I can do. VimFX has been discontinued and the reason it manages to steal keys from Firenvim probably is that it uses an old API that isn't available to Webextension. I can only recommend switching to a newer "vim-like" webextension: Surfingkeys, Tridactyl, Vim-Vixen or something else. I know webextensions aren't as good as XUL ones but you're only going to encounter more and more bugs if you keep using old, unsupported technologies :/.

**Comment by girst** [comment]
> VimFX has been discontinued 

I'm the current maintainer of vimfx. feel free to open a pull request ;-) it shouldn't be hard to adapt https://github.com/akhodakivskiy/VimFx/commit/073db9d06fa1855cae5be1ccf6d17368bd4ed3a4 to suit firevim.
