### ISSUE TITLE
Colorscheme is not applied (solarized8)

### ISSUE THREAD

**Issue by Stvad** [glacambre/firenvim#363]
- OS Version: mac x86-64
- Browser Version:  Firefox 73.0
- Browser Addon Version: 0.1.17
- Neovim Plugin Version: 0.1.17
- What I tried to do: apply colorscheme
- What happened: nothing: colorscheme stays the same white on black, even though `:colorscheme` reports that `solarized8` is applied. It works if called from my usual terminal.

Hey! I'm trying to figure out how to apply the colorcheme that'd work with Firenvim and I'm not succeeding. The colorcheme I'm using is https://github.com/lifepillar/vim-solarized8 

In #225 you mention that it can be because the theme does not support 24 bit colors. It is supported in case of solarized8. Would appreciate your help with figuring this out!

**Comment by glacambre** [comment]
solarized8.vim will only set guifg if [`(has('termguicolors') && &termguicolors) || has('gui_running')`](https://github.com/lifepillar/vim-solarized8/blob/5df7666374ead07a482605b53a0f36c27dc17e8d/colors/solarized8.vim#L77).  Could you try to `:set termguicolors` in your init.vim?

**Comment by Stvad** [comment]
Ah, I've previously tried doing it directly in the firenvim session, which didn't seem to help (any idea on why btw?).  
But if I add it to the `init.vim` that produces the effect (colors are not quite what I expected, but well, it works :)

Also what is the proper algorithm for propagating changes from the config to `firenvim` from `init.vim`? I tend to reload the page and click "reload settings" button and some combination of that works, but it feels a bit nondeterministic 😛

**Comment by glacambre** [comment]
`Reload settings` will only reload the "browser settings" which you specified with `g:firenvim_config` (so what elements/websites Firenvim should appear on, whether the external commandline should be used…). Reloading another change (e.g. changing your colorscheme) will require opening and `:q`'ing Firenvim twice (this is because Firenvim starts a Neovim process in the background for faster startup). Note that opening and `:q`'ing Firenvim will also reload the "browser config".

Thanks for pointing out that this was confusing, I'll try to make it clearer :).

**Comment by Stvad** [comment]
Ah I see. Wow, so I succeded by accident before :p. I think having a button/mapping for that would be helpful :)
