### ISSUE TITLE
Having trouble configuring firenvim to not takeover anything by default

### ISSUE THREAD

**Issue by ahal** [glacambre/firenvim#373]
- OS Version: linux x86-64
- Browser Version:  Firefox 74.0
- Browser Addon Version: 0.1.17
- Neovim Plugin Version: 0.1.17
- What I tried to do: Configure firenvim to `never` takeover by default, and then whitelist the sites I want it to work on. Here is my config:
```
{'localSettings': {
  '.*': {'priority': 0, 'takeover': 'never'},
  '.*phabricator\.services\.mozilla\.com.*': {'priority': 1, 'takeover': 'always', 'selector': 'textarea'},
  '.*bugzilla\.mozilla\.org.*': {'priority': 1, 'takeover': 'always', 'selector': 'textarea'},
  '.*mail\.google\.com.*': {'priority': 1, 'takeover': 'always', 'selector': 'div[aria-label="Message Body"]'}},
 'globalSettings': {'alt': 'all'}
}
```

I'm using Firefox Nightly.

- What happened: Firenvim takes over elements on domains not explicitly whitelisted, such as slack.com.

It's very likely this is user error and I just need to configure it differently. Though the README is a bit sparse when it comes to explaining how things like wildcards and the priority system work.

Otherwise, thanks for the awesome extension!

**Comment by glacambre** [comment]
Hi, thanks for opening this issue :).

>It's very likely this is user error and I just need to configure it differently. 

Actually, I think you got everything right. I don't see anything wrong in your settings, I can reproduce this issue on Firenvim 0.1.17 and I can't on the master branch, which makes me think this is the same bug as #308.

I think I managed to disable slack on my work laptop by using something like `'slack.com': { 'selector': '' }` but I can't get it to work on my personal computer.

>Though the README is a bit sparse when it comes to explaining how things like wildcards and the priority system work.

Yes, I tried to make it as terse as possible in order to get as many people as possible to read it in its entirety. What information is missing/not explained in enough depth in your opinion?
I tried to explain the wildcards by saying that they're "a Javascript pattern matching a URL". Would using the words "Regular Expression" be better (because that's what they are, just JS regexps)?
The priority system is explained with "When multiple patterns match a same URL, the pattern with the highest "priority" value is used." and "Notice how the priority of this new regex is higher than that of the .* regex", but again, I can see how this might not be super clear.

Feel free to open a PR if you find better ways to explain this :)

**Comment by ahal** [comment]
Ah, well if I had the config right then the docs must have worked after all :). I guess there could be a separate `CONFIGURATION.md` file that acts as a reference for all the configuration options, but probably not a huge deal.

In the meantime I'll wait for the new release with the fix from #308. I'll comment back here when it is and confirm whether or not it fixes my issue.

**Comment by glacambre** [comment]
Hi @ahal, I published a new release, let me know if it fixes your problem :)

**Comment by glacambre** [comment]
Issue is fixed AFAIK - feel free to reopen if you can still reproduce :).

**Comment by ahal** [comment]
Sorry was on vacation.

Yes this is fixed for me too. Thanks!
