### ISSUE TITLE
Chinese input does not behave properly...

### ISSUE THREAD

**Issue by kuochang** [glacambre/firenvim#409]
My workflow involves lots of typing on webpage and I love the plug in very much. However, When I typed non-English character(Chinese), those characters didn't show up immediately until I switch back to English and then type a character.

For example, when I type '中文', it only shows two 'highlight geen blocks' with no words. Then I switch to English and type whatever character. Finally, '中文' starts to show up. 

Does anyone have idea why does it happen? How can I resolve this? Cheers! 

---
- OS Version: mac x86-64
- Browser Version: Google Inc. Chrome 80.0.3987.87
- Browser Addon Version: 0.1.20
- Neovim Plugin Version: 0.1.20
---

**Comment by glacambre** [comment]
This probably happens because input events for chinese characters have their [isComposing](https://github.com/glacambre/firenvim/blob/f737118d9e31ee250c60609726137d405edbbfd4/src/NeovimFrame.ts#L125) flag set to true. Checking `isComposing` is necessary because the meaning of a character sequence can change as the sequence is typed (#200). I'll probably have to take a look at what Ace/CodeMirror do in order to fix this issue.

Thanks for reporting this issue :).

**Comment by kuochang** [comment]
Appreciate that. Looking forward to it! Thanks!

**Comment by glacambre** [comment]
I see you're using v0.1.20 on Chrome, so I assume you built it from source. Could you build master again and let me know if your problem disappeared?

**Comment by kuochang** [comment]
Sure, I'll rebuild it a couple of hours later and let you know...

**Comment by kuochang** [comment]
I "git clone" the latest code and built it again, and it works! My Chinese input works fine now. Thank you very much!

**Comment by glacambre** [comment]
Great, thank you for letting me know! :)
