### ISSUE TITLE
maximize and larger frame

### ISSUE THREAD

**Issue by brandonkal** [glacambre/firenvim#426]
Wasavi has the option to maximize. As far as I can tell this is not available in firenvim.

I'd also like the option to have a larger frame. For instance, the GitHub comment form textarea grows dynamically but the iframe if fixed at the initial (and small) size.

**Comment by glacambre** [comment]
>I'd also like the option to have a larger frame. For instance, the GitHub comment form textarea grows but the iframe if fixed at the initial (and small) size.

`:set lines=10` and `set columns=100` should work. Also, if you manage to grab the handle of the underlying textarea, changing its size should also change the size of the Firenvim frame.

>Wasavi has the option to maximize. As far as I can tell this is not available in firenvim.

You're right, this isn't possible yet. Gvim uses `:set lines=999` and `set columns=999` in order to let users maximize windows. I should probably catch this case an treat it as a maximize command.

Or perhaps a new extension should be implemented for window management, with support for maximization, fullscreen, `:winpos` and others. Perhaps it should be implemented along with https://github.com/neovim/neovim/pull/8707.

**Comment by brandonkal** [comment]
Thanks for letting me know about 1.

At least on GitHub I am able to resize the comment textarea by dragging the  bottom corner. But when it receives focus, it is reset to the smallest size. 

Wasavi has a set fullscreen command to maximize the iframe.

**Comment by glacambre** [comment]
>Wasavi has a set fullscreen command to maximize the iframe.

I would prefer to have Firenvim be consistent with Gvim/other Neovim GUIs rather than with wasavi :).

**Comment by glacambre** [comment]
If you're running master, you can now use `:set lines=100` and `:set columns=300` to ask Firenvim to create a frame as large as possible (note that if your browser window is larger than 100 lines and 300 columns, you'll have to ask for more).
Note that performance is very poor for now and will be improved by #347.

I'll probably publish a new release in the coming week.

**Comment by rightaway** [comment]
@glacambre I set this but I still can't expand the github issue text box vertically more than a few lines extra when creating a new issue.

Shouldn't it be a default setting to create the frame as large as allowed? So if you extend the text box vertically the vim window will always take up the full allowed space, because this would always be the desired behavior?

**Comment by glacambre** [comment]
@rightaway this works for me, could you describe exactly what you tried to do?
![file](https://user-images.githubusercontent.com/11534587/81163125-8bb14500-8f8e-11ea-878d-4e53d1e7e194.gif)

**Comment by rightaway** [comment]
I tried to put it in the config file to make it automatic, is it correct?

```
if exists('g:started_by_firenvim')
	set lines=100
	set columns=300
endif
```

**Comment by glacambre** [comment]
>I tried to put it in the config file to make it automatic, is it correct?

It's not, but I can't blame you for trying this :). Your `set lines=100` statement is executed before any screen exists and is thus overriden by Firenvim's first call to `nvim_ui_attach()`. Try setting this setting by using the [UIEnter](https://github.com/glacambre/firenvim#building-a-firenvim-specific-config) autocommand instead.

**Comment by rightaway** [comment]
I have this at the top of my vimrc to prevent loading unnecessary plugins in firenvim but it's not working. Some idea?

```
call plug#begin()
if exists('g:started_by_firenvim')
  Plug ...
  Plug 'glacambre/firenvim', { 'do': { _ -> firenvim#install(0) } }
endif
call plug#end()
```

**Comment by glacambre** [comment]
I don't know, I don't use vim-plug. Maybe it stores your plugins in your 
packpath/runtimepath?

**Comment by rightaway** [comment]
https://github.com/junegunn/vim-plug/wiki/tips#conditional-activation I thought wrong that a plugin is loaded based on whether it's in the vimrc. I didn't realize that even if it's not in the vimrc it's loaded as long as it's in the path. Is there any workaround you can think of I could try? Unfortunately it's almost unusably slow and laggy within firefox but works very well in regular terminal mode.

**Comment by glacambre** [comment]
A common pattern in vimscript plugins is to have a global variable 
`g:xxx_loaded` and to check if it exists - if it does, the plugin 
doesn't load. For example I know netrw has `g:loaded_netrw` and 
`g:loaded_netrwPlugin`, which you can both set to 1 in order to prevent 
netrw from loading. Perhaps you could check if the plugins you use have 
similar mechanisms?

**Comment by rightaway** [comment]
Unfortunately that doesn't work in this case. What if there were an option in the browser extension to put the path to another vim config file? Then we could have a completely independent vim running just for this, and `source` the common parts of configuration from a separate file.

**Comment by glacambre** [comment]
You can already do this yourself:

if exists("g:started_by_firenvim")
	source /home/me/.config/nvim/firenvim.vim
else
	source /home/me/.config/nvim/regular.vim
endif

**Comment by kevinhwang91** [comment]
@glacambre How can I make the nvim window center on the page?
Like fzf plugin create a floating window in native nvim.

**Comment by glacambre** [comment]
@kevinhwang91 You can't right now and I don't think this is a useful feature, so I'm not planning on implementing it. Feel free to provide arguments to convince me that I'm wrong though :)

**Comment by ahmedjaadi** [comment]
> I tried to put it in the config file to make it automatic, is it correct?
> 
> ```
> if exists('g:started_by_firenvim')
> 	set lines=100
> 	set columns=300
> endif
> ```

Place this in your `initi.lua` and it should do it
```
vim.api.nvim_create_autocmd("UIEnter", {
	callback = function()
		vim.opt.lines = 100
		vim.opt.columns = 300
	end,
})

```
