### ISSUE TITLE
better defaults

### ISSUE THREAD

**Issue by ocehugo** [glacambre/firenvim#459]
- OS Version: linux x86-64
- Browser Version:  Firefox 73.0
- Browser Addon Version: 0.1.21
- Neovim Plugin Version: 0.1.21

Great extension and very useful - thanks.

I just think the defaults should be better - ```takeover``` should never be ```always``` - given the security implications discussed. For example, a much less intrusive way is to just use ```never``` as default.

PS: Are the security implications the same if "never" is used!?

**Comment by glacambre** [comment]
>takeover should never be always - given the security implications 

I don't want to do this for three reasons:

- Firenvim would look like it is broken for users who are using the current defaults. This would interrupt their workflow and I hate when the tools I use do this, so I don't want to inflict this on Firenvim users.
- Firenvim users already have accepted the security implications of the default configuration when they installed Firenvim (these security implications are made really obvious, the first step of installing Firenvim is reading SECURITY.md).
- The risks are really low. The only thing attackers can do is a DOS attack. Performing this DOS attack would require creating ~60000 elements in the page (one for each port on the user's machine), which users would notice (Firefox/Chrome would become very slow). Creating ~60000 Firenvim elements wouldn't even be possible (I believe Firefox has a hard limit of 10 child processes on Windows and on Linux a process can't have more than `/proc/sys/kernel/pid_max`, which is usually a value lower than 30000). If things came to worst, the user would have to close their browser/reboot their machine, which doesn't benefit the attacker in any way and is only a mild annoyance to the victim.

>For example, a much less intrusive way is to just use never as default.

This is just personal preference and I prefer `takeover` to be `always` :).

>PS: Are the security implications the same if "never" is used!?

No, as Firenvim won't create new neovim instances when `takeover` is `never` :).

**Comment by ocehugo** [comment]
I understand, but let me express the good sides of it:

1. Using ```never``` is in line with several modern vim package managers, but applied to the browser - only load an extension when you want.
I could even suggest 1. that the extension sleep completely until someone press ctrl+e but browsers are not my thing or 2. A no "default keybinding" rule, but this may be too vim-esque.

>Firenvim users already have accepted the security implications of the default configuration when they installed Firenvim (these security implications are made really obvious, the first step of installing Firenvim is reading SECURITY.md).

 It's not about that, but about:

2. control of when extensions are allowed to operate. 

I personally feel much more safe from both the security/stability/privacy of my browser when I can "activate/deactivate" an extension (such as with ctrl+e).

>Firenvim would look like it is broken for users who are using the current defaults.

I don't think so - this is a very particular extension and with dual requirements (both extension and nvim package need to be installed).  People know what they are doing and probably would hit ctrl+e if firenvim is not open at a textbox.

3. Would help memory/performance perhaps!? I didn't use the extension much so far but how would it handle when several textboxes are loaded in several tabs (such as several github issue pages). In the worst-case scenario, it would have a lot of overhead

4. Would reduce states, processes, and hence crashes.

> This would interrupt their workflow and I hate when the tools I use do this, so I don't want to inflict this on Firenvim users.


Regardless of the reasons above, I would suggest you put a more straight-forward line in the code/wiki/docs for the ```takeover``` behaviour - ```let g:firenvim:auto_takeover_in_browser = 0|1``` - since this is an important option.

**Comment by glacambre** [comment]
>Using never is in line with several modern vim package managers, but applied to the browser - only load an extension when you want.

Webextensions are not vim plugins. WebExtensions will be loaded no matter what, there no concept of autoload (and given how dynamic JS is, it doesn't make sense to even try to think about implementing something similar) pretending otherwise would be wrong.

>I personally feel much more safe from both the security/stability/privacy of my browser when I can "activate/deactivate" an extension (such as with ctrl+e).

This is a false sense of security. Firenvim is activated, whether you press `<C-e>` or not and the same thing applies for all other extensions too. The only way to deactivate WebExtensions is to go to `about:addons` or `chrome://extensions`.

>>Firenvim would look like it is broken for users who are using the current defaults.
>I don't think so

If users are able to use Firenvim by clicking on a textarea one day and the following day they can't, without having done anything (because browsers silently update WebExtensions), Firenvim will look broken.

>In the worst-case scenario, it would have a lot of overhead

Please provide hard metrics, otherwise you're just speculating.

>Would reduce states, processes, and hence crashes.

Have you experienced Firenvim crashing on you?

>I would suggest you put a more straight-forward line in the code/wiki/docs for the takeover behaviour - let g:firenvim:auto_takeover_in_browser = 0|1

There already is a configuration mechanism which is more powerful and generic. Adding new, less flexible, ways to configure Firenvim is a bad idea. You might find it useful but I'm the one who will have to maintain that, and this is clearly not worth the cost for me.

**Comment by ocehugo** [comment]
>Webextensions are not vim plugins. WebExtensions will be loaded no matter what, there's no concept of autoload (and given how dynamic JS is, it doesn't make sense to even try to think about implementing something similar)

I think you know what I meant, you don't need to dumb down. This is the web extension most problematic thing, but I'm diverging.

> pretending otherwise would be wrong.

You said the implications are not the same so, with a ```never``` the security may be increased a little (even though it's just a crash reduced probability). But it is not even about that, but about being less intrusive, opt-in instead of opt-auto.

>If users are able to use Firenvim by clicking on a textarea one day and the following day they can't, without having done anything (because browsers silently update WebExtensions), Firenvim will look broken.

I agree, not the best thing in the world, but I still think this is not a big deal and feel like you are dumbing down on your already niche users. 

>otherwise you're just speculating.

Yes, as I put in the start of the sentence - Worst case scenario. The fact of having dozen of neovim instances, linked to a tab in a browser, is not a zero-cost memory oper or the most rock-solid thing in the universe. Your options already give a hint about it.

>Have you experienced Firenvim crashing on you?

No -which is great - thank you. However, it is a possibility and to negate (with a question) that is (more) naive since there are so many possibilities (browser, nvim, other nvim extensions, other browser extensions, firenvim, local libraries).

>There already is a configuration mechanism which is more powerful and generic. Adding new, less flexible, ways to configure Firenvim is a bad idea.

The suggestion was about being more direct/simple for an option that is the most changed one. Why do I have to climb a trunk, hold a branch, twist the twig and pick up the apple if you can just extend your arm!?

I don't think we need to discuss further - positions are very clear and I'm happy to agree to disagree.

**Comment by glacambre** [comment]
>I think you know what I meant,

No, I did not, and I apologize if you believe I replied in bad faith. I discovered that I can't assume anything about the amount of technical knowledge users have, even for a niche extension like Firenvim. This means that I have to take things very literally instead of trying to guess what users mean.

>I feel like you are dumbing down on your already niche users.

Trust me, I am not. There is a surprising amount of people with zero technical skills or willingness to use their brains to figure things out that use extensions geared towards "power users" like Firenvim or Tridactyl.

>>you're just speculating.
>Yes, as I put in the start of the sentence - Worst case scenario.

Worst case scenario, Firenvim increases the amount of CPU power used by computers, which increases global warming and will kill us all :). You have to draw a line somewhere, something being possible doesn't mean that it has a high probability of happening and something happening doesn't mean it is significant.

>The suggestion was about being more direct/simple for an option that is the most changed one.

Do you have data showing that this is the most changed option?

>Why do I have to climb a trunk, hold a branch, twist the twig and pick up the apple if you can just extend your arm!?

Because I'd rather have to maintain a truck than an orchard of tiny apple trees the fruits of which you'll only eat once :).

**Comment by glacambre** [comment]
And thank you for suggesting improvements, even if I disagree with them :).
