### ISSUE TITLE
VimLeave not always triggered

### ISSUE THREAD

**Issue by glacambre** [glacambre/firenvim#49]
After running [close_server](https://github.com/glacambre/firenvim/blob/198db7c4e303f2f74c020e238c6243fe0680b2c3/lua/firenvim.lua#L3-L8), nvim prompts `Press ENTER or type command to continue` on stderr. This might be related to https://github.com/neovim/neovim/issues/9358.
Could also be related to https://github.com/neovim/neovim/issues/11166.

**Comment by justinmk** [comment]
Assuming this is the same problem, but just for reference:

- Explicitly quitting Nvim via `:wq`, `ZZ`, `ZQ` seems to exit the process without issue.
- "Navigating away" without explicit exit, seems to leave `nvim.exe` running.

**Comment by svermeulen** [comment]
Yeah I just noticed this too.  After using it for awhile I find that I quickly end up with tons of nvim processes listed when I run `ps aux | grep nvim`.

**Comment by justinmk** [comment]
One solution/workaround could be to use Nvim's "external window" feature: 

1. connect to the same `nvim` instance from each textbox
2. instead of creating a new `nvim`, create a new external (floating) window on the connected `nvim` server.
  - `nvim_open_win` with `external=true`. Requires `:help ui-multigrid` to be enabled.
3. focus the window 

Caveats:

- this will create many windows in the Nvim server, but that should scale up to thousands without a problem. 
- if user somehow navigates out of the window, will be confusing.
- user can't create split windows in an external window. 

Alternative: "tabgrid" feature (not merged yet) https://github.com/neovim/neovim/pull/7541

**Comment by glacambre** [comment]
I added a workaround to kill lingering neovim processes with `os.exit()` when `:qall!` doesn't work. This means that you should now see at most 2 neovim processes belonging to firenvim: one for the textarea you're editing and another for the next textarea you'll edit.

I might be wrong but I think that in cases where `os.exit()` is used, autocommands such as VimLeave won't be triggered.

@justinmk I'll probably implement your idea with https://github.com/glacambre/firenvim/issues/197 .

**Comment by NilsIrl** [comment]
This is also problematic as `nvim` prevents shutdowns.

**Comment by justinmk** [comment]
> `nvim` prevents shutdowns

? shutdown of what?

**Comment by NilsIrl** [comment]
> ? shutdown of what?

The computer. If I run poweroff/shutdown/reboot/systemctl ....

I get the message `A stop job is running for Session x of user xxxx (1min 30s)` and have to wait 1min 30s for my computer to power off. This is caused by having lingering `nvim` instances.

```
Jan 02 21:16:49 nixos systemd[1]: session-1.scope: Stopping timed out. Killing.
Jan 02 21:16:49 nixos systemd[1]: session-1.scope: Killing process 10196 (nvim) with signal SIGKILL.
```

I can confirm that this is the case because when I manually `kill` the `nvim` instances, this doesn't happen. These instances are created by `firenvim` and never removed even when Firefox is closed.

**Comment by glacambre** [comment]
This should be fixed with https://github.com/neovim/neovim/commit/a2efc9cf8b0fdf14b01156ba424145e1847f789c - thanks @justinmk!

I'll keep this issue open for a few weeks, please let me know if you can still reproduce this bug with a neovim that has patch a2efc9c.

**Comment by glacambre** [comment]
Can still reproduce. This is weird, I could have sworn this was fixed.

**Comment by justinmk** [comment]
@glacambre maybe https://github.com/neovim/neovim/commit/ce15977d708886a3d55fa21127abc7145dc7aaf8 helps?

**Comment by glacambre** [comment]
It was actually fixed for a brief instant, after https://github.com/neovim/neovim/pull/11821 was merged and before I merged #382. I pushed a fix to master and this should now properly be fixed again. Keeping this issue open until I add a test that makes sure it stays fixed :)

**Comment by justinmk** [comment]
Recently I've noticed that unsaved changes do not get written to the browser textbox when exiting via `ZZ` with firenvim. Using Nvim HEAD at https://github.com/neovim/neovim/commit/d0835617facc . 

Haven't bisecting anything yet, just wondering if others are seeing this.

**Comment by glacambre** [comment]
@justinmk I can't reproduce on 1b235fe6c . I'll take a deeper look this week-end.

**Comment by justinmk** [comment]
Fixed by https://github.com/glacambre/firenvim/pull/1384 ?

**Comment by glacambre** [comment]
@justinmk Indeed, I can't repro on neovim master, so if you can't either let's assume this is fixed :)

**Comment by tricktux** [comment]
Exiting via `ZZ` does not save text for me. I have to `:wq`

firenvim version: Not sure how to see, installed from the firefox store
OS: Archlinux
Firefox version: 120.0.1 (64-bit)
nvim version: 
NVIM v0.10.0-dev-1870+g8fb7419d7c
Build type: RelWithDebInfo
LuaJIT 2.1.1702233742
Run ":verbose version" for more info

**Comment by glacambre** [comment]
@tricktux Could you go in insert mode in Firenvim and run 
```
:redir @a
:map Z
:map ZZ
:au VimLeave
:redir END
```
And then press `"ap` in order to insert your mappings/VimLeave autocommands in the buffer and then give me the results?

**Comment by tricktux** [comment]
Hi @glacambre

Thanks for the quick response! Amazing extension BTW!

Here's the output:

```
x  Z             <Plug>Sneak_S
o  Z             <Plug>Sneak_S

--- Autocommands ---
FirenvimAugroupChan3  VimLeave
    *         call rpcnotify(3, 'firenvim_vimleave') | call delete('github.com_glacambre-firenvim-issues-49_TEXTAREA-id-new-comment-field_2024-01-12T20-08-17-430Z.txt')

```
