### ISSUE TITLE
Manual trigger shortcut does not work when takeover=never

### ISSUE THREAD

**Issue by Stvad** [glacambre/firenvim#504]
- OS Version: macOS 10.14.6
- Browser Version: Chrome 80.0.3987.163, Firefox 76.01 (happens for both)
- Browser Addon Version: 0.1.23
- Neovim Plugin Version: 0.1.23
- What I tried to do: I want to set up the Firenvim to work "on demand" i.e. disabled by default, and me being able to trigger it using the keyboard shortcut
- What happened: After setting takeover mode to `never` pressing the shortcut won't activate the plugin anymore. The text field would get surrounded by the black frame for a while blocking interaction but then will go back to being a regular text field.

![Screen Shot 2020-04-12 at 2 31 31 PM](https://user-images.githubusercontent.com/81347/79080517-6ea88f80-7cca-11ea-8512-9e29b9cb414e.png)

**Comment by glacambre** [comment]
It looks like your init.vim is broken and preventing Firenvim from starting neovim and thus fetching your settings.

First, does Firenvim work at all when using a default config? (see [this](https://github.com/glacambre/firenvim/blob/master/TROUBLESHOOTING.md#make-sure-its-not-your-initvim))
If yes, could you try to [print-debug](https://github.com/glacambre/firenvim/blob/master/TROUBLESHOOTING.md#print-debugging-your-initvim) your init.vim?

**Comment by Stvad** [comment]
Ah you're right. I was trying to modify my config by having the following in my init.vim

```
  let fc = g:firenvim_config['localSettings']
  let fc['.*'] = { 'takeover': 'never' }
```

Assuming that it'd override the default value. But it seems I need to redefine the whole config manually before I can do that - this is confusing. 

Btw now that I have changed that I have another issue: the shortcut works the first time, but if I exit vim and try to use it the second time it does not do anything.

**Comment by glacambre** [comment]
>But it seems I need to redefine the whole config manually before I can do that - this is confusing.

I've updated the readme to make this clearer, thanks for pointing out this issue :).

>the shortcut works the first time, but if I exit vim and try to use it the second time it does not do anything.

I can't reproduce this issue. Can you reproduce it on https://txti.es with a clean browser profile?

**Comment by Stvad** [comment]
>I've updated the readme to make this clearer, thanks for pointing out this issue :).

Thanks for updating that, I don't think it's very discoverable still though. Would it be possible to have a behaviour something like:
* If that variable is not explicitly defined - define it and assign default values to it

That way people can just override what they want on the defaults, and it seems like a more intuitive behaviour to me.

>I can't reproduce this issue. Can you reproduce it on https://txti.es with a fresh browser profile?

I can reproduce it both in Chrome and Firefox, tried the incognito mode as well.
Here is my current section of `init.vim` related to firenvim:

```
"""firenvim config
let g:dont_write = v:false
function! My_Write(timer) abort
	let g:dont_write = v:false
	silent write
endfunction

function! Delay_My_Write() abort
	if g:dont_write
		return
	end
	let g:dont_write = v:true
	call timer_start(1000, 'My_Write')
endfunction

au TextChanged * ++nested call Delay_My_Write()
au TextChangedI * ++nested call Delay_My_Write()

"paste
nnoremap <D-v> "+p
inoremap <D-v> <C-r>+

set termguicolors

if exists('g:started_by_firenvim')
  nnoremap <Esc><Esc> :call firenvim#focus_page()<CR>
  "
  "let fc['.*'] = { 'cmdline' : 'firenvim' }
  let g:firenvim_config = { 
    \ 'globalSettings': {
        \ 'alt': 'all',
    \  },
    \ 'localSettings': {
        \ '.*': {
            \ 'cmdline': 'firenvim',
            \ 'priority': 0,
            \ 'selector': 'textarea, ''textarea, div[role="textbox"]',
            \ 'takeover': 'never',
        \ },
    \ }
  \ }
  let fc = g:firenvim_config['localSettings']

  set guicursor=a:block-blinkon0
endif


" website specific settings
au BufEnter github.com_*.txt set filetype=markdown
au BufEnter hire.amazon.com_*.txt set filetype=markdown

"let fc['^https?://twitter\.com/'] = { 'takeover': 'never', 'priority': 1 }

" https://github.com/glacambre/firenvim/issues/366
let $LANG='en_US.UTF-8'**
```

**Comment by glacambre** [comment]
>That way people can just override what they want on the defaults, and it seems like a more intuitive behaviour to me.

You can already do this, if you do something like `let g:firenvim_config = { 'localSettings': { '.*': { 'takeover': 'never' } } }`, firenvim will use default values for everything except `takeover`. I would prefer to avoid defining a `g:firenvim_config` object if it's not needed to avoid polluting the user's environment.

>I can reproduce it both in Chrome and Firefox, tried the incognito mode as well.

I can too. The issue comes from your config - `'selector': 'textarea, ''textarea, div[role="textbox"]',` is not a valid CSS selector. This results in an exception being thrown and assumptions being invalidated. Since it looks like you want the default selector anyway, you can just remove this line from your config and Firenvim should start behaving as you expect it to.

I'll implement a message to let user know about invalid CSS selectors.

**Comment by Stvad** [comment]
> You can already do this
I see, having the variable defined would be more intuitive IMO, and I don't think having 1 variable is polluting the env. 🤷

>The issue comes from your config

Ah 🤦‍♂️. Yeah feedback on incorrect config would be great!

**Comment by rightaway** [comment]
Do I set `let g:firenvim_config = { 'localSettings': { '.*': { 'takeover': 'never' } } }` within both OnUIEnter and g:started_by_firenvim? It's not working for me.

But really shouldn't the takeover and selector settings be a part of the browser extension settings and not the vim config file? If the browser config settings show that there's no selector on the page or takeover is no, then it wouldn't even need to touch and vim functionality? And the vim config can just be for things that appear once a vim window is actually running.

**Comment by glacambre** [comment]
On 2020-05-06 13:19, rightaway wrote:
> Do I set |let g:firenvim_config = { 'localSettings': { '.*': { 
> 'takeover': 'never' } } }| within both OnUIEnter and 
> g:started_by_firenvim? It's not working for me.

No, just set it somewhere in in your init.vim, like you would set any 
other setting.

> But really shouldn't the takeover and selector settings be a part of the 
> browser extension settings and not the vim config file?

Ideally, yes. Unfortunately browser settings aren't easy to store in a 
git repository or to control programmatically, so I decided to make them 
live in init.vim instead.

> If the browser config settings show that there's no selector on the page
> or takeover is no, then it wouldn't even need to touch and vim > functionality?

Checking settings you have in your init.vim is "free": in order to not 
be painfully slow, Firenvim has to "preload" a neovim instance. It 
fetches settings from this preloaded instance.

> And the vim config can just be for things that appear once a vim window > is actually running.

This is impossible to implement. Firenvim uses websockets in order to 
communicate with neovim. In order for neovim to open websockets, it has 
to have loaded the Firenvim neovim plugin. In order for the firenvim 
neovim plugin to open the socket, it has to read your settings. So your 
`g:firenvim_config` object has to exist before any window exists.
