### ISSUE TITLE
Autosave automatically focuses Neovim

### ISSUE THREAD

**Issue by Shatur95** [glacambre/firenvim#512]
- OS Version: ArchLinux x86-64
- Browser Version:  Firefox 75.0
- Browser Addon Version: 0.1.24
- Neovim Plugin Version: 0.1.24
- What I tried to do: `autocmd FocusLost * ++nested write`.
- What happened: With this `autocmd` after changing focus to the page it automatically saves the buffer (expected) and changing focus to Neovim back (not expected). So, the focus becomes broken, I can focus page with this `autocmd` :(

**Comment by glacambre** [comment]
Can reproduce - thanks for the bug report. I'll investigate soon :).

**Comment by glacambre** [comment]
Closed by f7b35f1 . If you build the browser plugin from source, you'll be able to benefit from the fix immediately. If instead you've downloaded the plugin from addons.mozilla.org, you'll probably have to wait a couple of weeks until I release v0.1.25.

This issue was introduced in firenvim v0.1.24, which I released yesterday. Even though v0.1.24 is already available on addons.mozilla.org, it has yet to go through a review on the Chrome web store and Chrome's review process is quite slow. I can't publish v0.1.25 on the Chrome web store until v0.1.24 has been published and I want to keep Firenvim versions available to Chrome and Firefox in sync.

Again, thanks for reporting this bug! :)

**Comment by Shatur95** [comment]
Thank you for the quick fix and explanation about how publishing works. I will try to build plugin from source to provide a feedback.

**Comment by Shatur95** [comment]
Tested just now, it works as expected, thank you!
