### ISSUE TITLE
focus_page() doesn't work with plugins like vim-vixen

### ISSUE THREAD

**Issue by AtomToast** [glacambre/firenvim#537]
- OS Version: linux x86-64
- Browser Version: Firefox 75
- Browser Addon Version: 0.1.27
- Neovim Plugin Version: 0.1.27
- What I tried to do:
  1. use my keybind (esc+esc) to focus the page
  2. use any vim-vixen shortcuts
- What happened:
  1. firenvim window got unfocused
  2. the page got a dotted outline
  3. no vim-vixen keybinds work
  4. clicking on the page makes it work again
     also pressing tab opens a blue box in the top left of my screen saying "skip to content" after that pressing any key also makes vim-vixen work again

I don't know what exactly focus_page() focuses but it does not seem to be the thing vim-vixen needs focused in order to work

**Comment by glacambre** [comment]
Firenvim focuses the page, i.e. the documentElement:
https://github.com/glacambre/firenvim/blob/0c1a091701764ab900788ad49ed89aaa4cc7e787/src/page/functions.ts#L44-L47

Vim-vixen only attaches event listeners to the body:
https://github.com/ueokande/vim-vixen/blob/8b9388f6e60fe67d20638f55aecb0ed1b281871a/src/content/Application.ts#L115

I can't focus the body element because Chrome has restrictions as to what elements can be focused by javascript.

Vim-vixen should probably do what Tridactyl does and listen for events on windows:
https://github.com/tridactyl/tridactyl/blob/8a5411432bc70b9062b2f8fbddea5a2a27537644/src/content.ts#L77

**Comment by glacambre** [comment]
I've opened https://github.com/ueokande/vim-vixen/issues/748 - I'm going to close this issue as I believe Firenvim does the right thing here.
