### ISSUE TITLE
Ignore readonly textareas by default

### ISSUE THREAD

**Issue by BlueDrink9** [glacambre/firenvim#564]
This is something that users can probably do themselves, but making every user do something just to keep your own codebase cleaner seems wrong to me.

Example element:

```html
<textarea class="qBHUIf" readonly="" jsname="feLNVc"
    jsaction="focus:O1htCb;">4/redacted</textarea>
```

**Comment by glacambre** [comment]
Hah, interesting, `disabled="true"` elements do not trigger focus events 
but `readonly=""` ones do. It indeed makes sense to disable these by 
default :).

On 2020-05-15 10:14, BlueDrink9 wrote:
> This is something that users can probably do themselves, but making 
> every user do something just to keep your own codebase cleaner seems 
> wrong to me.

Do you feel I have taken this approach wrt other issues?

**Comment by BlueDrink9** [comment]
Awesome, thank you

> Do you feel I have taken this approach wrt other issues?

This is my opinion only (and in every case I respect yours) but I did feel this was your approach (to some extent) with the Mac mapping `cmd+v` issue (#551), and definitely earlier on with your hesitance to add `g:started_by_firenvim` (forcing everyone to `au uienter`), and with providing default filetypes for commonly-used websites (#268).

Don't get me wrong, I appreciate that every little bit of extra code in the codebase just increases your maintenance burden, and I totally support anywhere you choose to keep that minimal (even if I support it for selfish reasons like not wanting the project to die).

The reason I mentioned it was as the initial argument for including it (since my experience is you do want things justified before you include them, which is a good thing), since I'd already acknowledged there was a user-only alternative.

**Comment by glacambre** [comment]
On 2020-05-16 00:33, BlueDrink9 wrote:
> This is my opinion only (and in every case I respect yours) but I did 
> feel this was your approach (to some extent) with the Mac mapping 
> |cmd+v| issue (#551 <https://github.com/glacambre/firenvim/issues/551>)

The decision I made here wasn't to keep my code simple, but rather to 
keep Firenvim "unopiniated". I have the belief that Neovim GUIs (and 
just any tool in general) should make more things possible while not 
making any decisions on behalf of the user.
I agree that there are times where I strayed away from this philosophy 
(e.g. providing defaults that enable Firenvim everywhere) and I regret 
these as they're very hard to undo (I'm waiting for the need of a 
breaking change that would force users to read documentation).
I'll also add that undoing keybindings created by Firenvim would be 
complicated for users, instead of being able to add an `inoremap <D-v> 
…` line anywhere in their init.vim, they would specifically have to add 
them through the UIEnter autocommand.

> and definitely earlier on with your hesitance to add 
> |g:started_by_firenvim| (forcing everyone to |au uienter|),

FWIW, I believe I was right. I think 
https://github.com/glacambre/firenvim/issues/426#issuecomment-624548213 
proved that people don't want to read documentation and thus don't 
understand the way Firenvim works. Forcing them to do the right thing 
(setting Firenvim-specific settings in UIEnter) would have prevented 
this problem from happening. Moreover, UIEnter is just so much more 
flexible than g:started_by_firenvim! You could start a neovim session in 
your terminal and then connect to it from the browser, 
g:started_by_firenvim won't be defined there, but UIEnter will trigger. 
UIEnter clearly was and is the correct solution IMO :).

> providing default filetypes for commonly-used websites (#268 
> <https://github.com/glacambre/firenvim/issues/268>).

I would say you are right here, I was against that idea mostly because I 
didn't want the burden of having to maintain a list of filetypes and in 
the end I was wrong.

> for selfish reasons like not wanting the project to die).

It's free software, it can't die as long as someone is sufficiently 
interested in keeping it alive ;).

> The reason I mentioned it was as the initial argument for including it 
> (since my experience is you do want things justified before you include 
> them, which is a good thing), since I'd already acknowledged there was a 
> user-only alternative.

Thank you for the feedback, it's interesting to go back over previous 
decisions and see how they were percieved/how I feel about them now :).

**Comment by BlueDrink9** [comment]
Thank you for the comprehensive reply. It is indeed interesting to see the differences in how I interpreted things vs what you meant/intended.

> undoing keybindings created by Firenvim would be
complicated for users

This is a very good point. If I think about it, I'm pretty sure I couldn't remap cmd + v on macvim. And as I mentioned in the original issue, I was happy to accept your response to it.

> FWIW, I believe I was right. I think #426 (comment)

Oh dear, yes that does seem like a hassle. Personally I actually used both for a while, with a check for `g:started_by` used to skip evaluating the setup code for firenvim. I've since swapped out the bulky uienter code and checking for a simple `au bufenter`, which is possible because of the var. I suspect you aren't the only plugin that has had support issues because a user tries to set something on startup that needs to be set in an autocmd.

> UIEnter clearly was and is the correct solution IMO

Did you have to add much code to support `UIEnter`? My (unresearched) understanding was that nvim did the lifting there, and all you needed to do was supply the info - the effect being that users could basically have used UIEnter regardless.

Plus, as I mentioned above, there are some things that the variable allows that `UIenter` doesn't, so I still don't agree with you that it was "the [one] correct solution".

> maintain a list of filetypes

I think this was the main example in my mind, because it was a big list to maintain for either you or users.

> It's free software, it can't die as long as someone is sufficiently
interested in keeping it alive

Yes indeed. My point was a large complicated codebase was more likely to put people off being interested. Honestly though I don't see firenvim dying any time soon because of how amazing it is for programmer types.

Anyway, you've satisfied me that my perception of those decisions came mostly from not understanding the reasons behind them.

**Comment by glacambre** [comment]
On 2020-05-17 02:08, BlueDrink9 wrote:
> Did you have to add much code to support |UIEnter|? 

No, UIEnter required no code on Firenvim's side. That's why it was so 
great, it did the right thing by default and I didn't even need to write 
any code :).

> Plus, as I mentioned above, there are some things that the variable 
> allows that |UIenter| doesn't.

Anything that can be done with `g:started_by_firenvim` can be done with 
`UIEnter`. The only downside of UIEnter is that it is indeed bulkier but 
this downside is eventually going to disappear: 
https://github.com/neovim/neovim/pull/11263.

**Comment by BlueDrink9** [comment]
> anything that can be done with `g:started_by_firenvim`

I might be missing something, but `UIenter` fires after vim initialisation, doesn't it? I.e. only when the UI is ready to connect? Otherwise, you couldn't have an autocmd in your `init.vim` that triggered it. That's what the variable adds: you know _from startup_ whether you are going to be firenvim.

> the only downside of UIEnter is that it is indeed bulkier but
this downside is eventually going to disappear

:(

**Comment by BlueDrink9** [comment]
Thank you for taking the time to discuss this with me btw, I appreciate it

**Comment by glacambre** [comment]
On 2020-05-17 08:35, BlueDrink9 wrote:
> I might be missing something, but |UIenter| fires after vim 
> initialisation, doesn't it? I.e. only when the UI is ready to connect? 
> Otherwise, you couldn't have an autocmd in your |init.vim| that 
> triggered it. That's what the variable adds: you know /from startup/ 
> whether you are going to be firenvim.

Why do you need to know whether you are going to be in Firenvim? UIEnter 
is triggered whenever a UI - and that includes the TUI - connects to 
Neovim. So if there's something you want to enable only in Firenvim, 
check if v:event matches Firenvim. If you want something that is enabled 
everywhere except in Firenvim, check that v:event doesn't match 
Firenvim. If you want something that is only enabled in the TUI, check 
that v:event matches the TUI.

The beauty of this is that it works the same way for all UIs, you don't 
need UI maintainers to add a bunch of ad-hoc variables (firenvim uses 
`g:started_by_firenvim` but Fvim has `g:fvim_loaded`, veonim has 
`g:veonim`, neovim-gtk has `g:GtkGuiLoaded`…).

**Comment by BlueDrink9** [comment]
I agree the variables are very messy, but say you don't want a bunch of plugins (and associated startup-cost, speed impacts during use, ui modifications like autocomplete, etc). If you use a plugin manager, you specify which plugins to load in your init.vim. Anything that you set in your init.vim that can't be changed in an autocmd (like g:option for foo plugin, or loading the plugin yourself) can't be altered by UIEnter.

**Comment by glacambre** [comment]
On 2020-05-17 09:20, BlueDrink9 wrote:
> I agree the variables are very messy, but say you don't want a bunch of 
> plugins (and associated startup-cost, speed impacts during use, ui 
> modifications like autocomplete, etc).

Plugins that have a startup cost should be rewritten to make use of 
vim's autoload features, which are designed to make loading plugins fast 
and painless.

Plugins that make UI modifications/have a speed impact during use should 
be toggleable at runtime. If a plugin makes Neovim acceptably slow in 
normal conditions and once in a while you need to perform a 
computationally expensive job that makes using the plugin unacceptably 
slow, you should be able to disable that plugin temporarily without 
having to restart your editor.

> If you use a plugin manager, you specify which plugins to load in your init.vim.

Loading plugins can be done at any time, including when the UIEnter 
event is triggered. Loading a plugin just means adding the path of the 
directory that contains the plugin to your `runtimepath` setting. If 
your plugin manager doesn't let you do that, your plugin manager has 
arbitrary limitations and it shouldn't be Firenvim's job to work around 
them.

We have this tradition in "software engineering" where we keep layering 
bad decisions on top of bad decisions to work around inadequacies in 
other systems rather than fix the problem at the source. This is how we 
end up with kludgey, buggy, slow software and it makes me sad :(.
