### ISSUE TITLE
Firenvim window sometimes stays in top left of the page

### ISSUE THREAD

**Issue by xerus2000** [glacambre/firenvim#635]
- OS Version: linux x86-64
- Browser Version:  Firefox 78.0
- Browser Addon Version: 0.1.30
- Neovim Plugin Version: 0.1.30

![image](https://user-images.githubusercontent.com/13354331/86904132-8ac49d00-c110-11ea-824c-3f8440653e14.png)

Here is how I can reproduce this, every time:
- go to any github issue
- click in the comment box to open firenvim
- click on "Code" in the navigation bar

The firenvim then moves to the top left, along with its contents. When I click on "Issues", it vanishes.
I guess that has something to do with the page not fully reloading?

**Comment by glacambre** [comment]
Oh, this only happens if the Firenvim element leaves the viewport before you click on "Code". When this happens, the intersection observer I use to keep track of whether the underlying input field is visible or not won't trigger when the page changes and that's why the Firenvim frame stays where it is.

Should be easy to fix by adding a mutation observer.

**Comment by glacambre** [comment]
Finally patched in master - the fix will reach you when I publish a new version. Thanks for reporting this bug! :)
