### ISSUE TITLE
Allow removing status bar in init.vim/.vimrc

### ISSUE THREAD

**Issue by mpinkert** [glacambre/firenvim#686]
I have tried turning off the vim status bar automatically using the command `set laststatus=0` in configuration files.  This does not work if it is put into `init.vim` or `.vimrc`.  I have tried this in both windows and mac firenvim installations.  For some reason, this command is overwritten after firenvim is called.

The only solution I have found so far is to directly edit the `.local/share/firenvim/firenvim` file to add a `-c 'set laststatus-0'` on the end.  You can also call it manually after opening an editor.

**Comment by glacambre** [comment]
I've always used `set laststatus=0` in firenvim and it works fine. Lots of people have been using it too (e.g. I'm not the one who wrote these examples: https://github.com/glacambre/firenvim#building-a-firenvim-specific-config ) so I'd say the problem is in your config. What does `:verbose set laststatus` say when you run it in firenvim?

**Comment by mpinkert** [comment]
I'm so sorry for missing that example.  It turns out a plugin (airline) was overriding the last status command.  I've turned off the plugin and not it works fine.

`Last set from ~/.vim/bundle/vim-airline/plugin/airline.vim`

Thank you for your help troubleshooting!
