### ISSUE TITLE
Firenvim keeps losing focus on fixed modals

### ISSUE THREAD

**Issue by lucax88x** [glacambre/firenvim#694]
- OS Version: linux x86-64
- Browser Version: Google Inc. Chrome 84.0.4147.135
- Browser Addon Version: 0.1.30
- Neovim Plugin Version: 0.1.30
- What I tried to do:
  using firenvim inside a fixed modal
- What happened:
  keeps losing the focus whatsoever

Here you can see a short video

https://webm.red/view/ccL9.webm

Why is this happening? because of a fixed modal? Or what?

BTW, I installed firenvim yesterday, and I'm just AMAZED about how good this is working generally, great job dude.

**Comment by glacambre** [comment]
This usually happens when the page tries to do something when the underlying element is blurred. I think this is what's happening here:

- You click on the text area
- Focus event is triggered on text area
- Firenvim appears, grabs focus from text area
- Blur event is triggered on text area
- Page decides to focus another element on blur (probably to allow for keyboard shortcuts)
- Blur event is triggered for firenvim

Fixing this is hard because Firenvim can't tell whether blur events are triggered by the user or the page.

**Comment by lucax88x** [comment]
I tried to add some logs for focus blur from the modal textarea, and it's NOT triggering any blur event after nvim appears :(

Same behavior for the first textarea.

Well, I guess it's really hard without a repro case.. let me try to do some codesandbox.

**Comment by glacambre** [comment]
>and it's NOT triggering any blur event after nvim appears :(

Blur events have to be triggered - firenvim calls `.focus()` on itself and this makes browsers trigger a blur event on the previously focused element. Same thing happens for the rest of the page - the page only calls `.focus()` on one of its elements and browsers automatically trigger a `blur` one for firenvim.

**Comment by lucax88x** [comment]
Yeah, this is working.

[sandbox](https://7k31s.csb.app/)

Must be my app, sorry for bothering you.

Thanks,
Luca

**Comment by glacambre** [comment]
>Must be my app, sorry for bothering you.

You're not bothering me :). This is an issue that people complain about frequently, I hope one day I'll see a pattern arise and find a way to fix it.

Do not hesitate to open issues in my repos when you encounter problems :).

**Comment by lucax88x** [comment]
Guess what, not even my app fault.

Material UI fault, rollbacking version to 4.2.1 works, from 4.3.0 it breaks :(

Just for future, in case anyone will ever use a Firenvim, inside a dialog, with a material ui react app, probably never :D
