### ISSUE TITLE
File from text-area on play.kotlinlang.org gets .c extension

### ISSUE THREAD

**Issue by silmeth** [glacambre/firenvim#720]
- OS Version: linux x86-64
- Browser Version:  Firefox 81.0
- Browser Addon Version: 0.1.31
- Neovim Plugin Version: 0.1.31
- What I tried to do:
  I added `autocmd BufEnter play.kotlinlang.org_*.txt set filetype=kotlin` to my `init.vim` expecting it
  would set `filetype` as `kotlin` on https://play.kotlinlang.org – the Kotlin playground.
- What happened:
  The autocmd did not work because the file weirdly got a `.c` extension: `play.kotlinlang.org__-2-DIV-1-DIV-1-DIV-1-DIV-2-DIV-1.c`

  I can of course get it to work by changing the `BufEnter` event pattern to expect `.c` extension or ignore
  it completely. But I think the `.c` extension for a text area not related to C in any way probably
  isn’t expected behaviour – I’d expect either the generic `.txt` or maybe `.kt`, so I report this issue. :)

**Comment by glacambre** [comment]
Thank you for the report :). Unfortunately, I believe there's nothing I can do: play.kotlinlang.org uses CodeMirror. When setting up CodeMirror, the website uses CodeMirror's "c-like" highlighting mode. Firenvim then retrieves the highlighting mode and uses that as an extension.

I can't make Firenvim use `.txt` for the "c-like" mode because this would break C and C++. The only solution I can see is to add a kotlin-specific mode to CodeMirror instead of using the c-like one.
