### ISSUE TITLE
Any way to use the run nvim to edit directly and exit nvim go back to the broswer? 

### ISSUE THREAD

**Issue by woshichuanqilz** [glacambre/firenvim#722]
Seems it wil be great if I can run nvim to edit when active a textbox in broswer. And when I exit the nvim the text I edit just now will fill in the certain textbox anyway to do it ?

**Comment by glacambre** [comment]
>I can run nvim to edit when active a textbox in broswer
I don't understand what you mean. Firenvim starts neovim as soon as a textbox is focused. If this doesn't happen for you, there is probably a configuration issue on your side.

>when I exit the nvim the text I edit just now will fill in the certain textbox anyway to do it
If you use `:wq`, the text should be inserted in the textbox. If you want to do this when moving the focus away from Neovim, you could try [this](https://github.com/glacambre/firenvim#automatically-syncing-changes-to-the-page). Know that some sites react very badly to this and you might end up in loops where the websites tries to focus the textbox and Firenvim tries to focus neovim.

**Comment by woshichuanqilz** [comment]
I mean when I active a textbox, I want auto start a terminal and run a nvim to edit the text.

Because I feel a little lag in firenvim maybe I feel wrong Just a personally feeling. But edit in terminal make me feel better.

And since I use some color theme in the browser the nvim appearance is not that good as in terminal. 

Though I set the textbox size when I trigger firenvim, but some textbox size cant be changed for example edit in the tiddlywiki page, I dont know if you use it.  

These 3 reason make me think open a terminal with nvim to edit is better

**Comment by glacambre** [comment]
>I mean when I active a textbox, I want auto start a terminal and run a nvim to edit the text.

There are lots of extensions that already do this (e.g. [GhostText](https://github.com/GhostText/GhostText)) so I don't see the point of implementing this in Firenvim.

>Because I feel a little lag in firenvim maybe I feel wrong Just a personally feeling.

There is indeed lag in Firenvim. I'm working on fixing some of it (see https://github.com/glacambre/firenvim/issues/347 for more information) but it takes time and some of the lag can't be fixed (because Neovim's RPC mechanism is inherently laggy).

>some textbox size cant be changed for example edit in the tiddlywiki page

Have you tried using `:set lines=20` and `:set columns=200` to change the size of the neovim frame?
