### ISSUE TITLE
How to debug press_keys?

### ISSUE THREAD

**Issue by BlueDrink9** [glacambre/firenvim#723]
I'm trying to use `inoremap <CR> <Esc>:w<CR>:call firenvim#press_keys("<LT>CR>")<CR>ggdGa` with Gitter, but it doesn't seem to be working.

Do you have any suggestions for how I might go about debugging what the underlying box gets sent? Or how it reacts to it?

**Comment by glacambre** [comment]
I don't have any better advice than "jump in with the debugger" :/.

Here's what I did to figure out what's wrong:
- Opened the page with Firefox's debugger
- Selected the element inspector and clicked on Gitter's textarea
- Clicked on the "events" button that hovers next to the element in the element inspector
  * First useful piece of information: Firefox shows event listeners attached to the element (so we know we've got the right one). There's one that belongs to Firenvim (the focus one, this confirms that we are seeing the element Firenvim will send the events to) and 2 keydown and 1 keyup events that belong to the page.
- Clicked on the "open in debugger" button of one of the keydown events and was disappointed to see that it's minified code without source maps.
  * Firefox is pretty useless to debug minified code without source maps, so I decided to switch to chrome.
- In Chrome's debugger, I opened the file named vendor.chunk.js (got the name from firefox's debugger), prettified the code and started looking for the string `throw a._ignoreNextOnError`.
  * I got this string from the code preview shown in Firefox's element inspector
- I was lucky to get only one match, in a function named `n` defined inside another named `wrap`. Decided to put a breakpoint at the beginning of `wrap`.
- Tried to trigger a keydown event. Unfortunately a lot of other events (focus, mouseout…) were triggered. Made the breakpoint conditional on not being an event I didn't care about.
- Tried to trigger a keydown event again. This time I got what I needed and so I pressed the `Step into next function call` button.
  * At this point I had to step through a mountain of boilerplate (which probably comes from Vue.js, the framework Gitter uses for its UI) in order to find useful code.
- Found a piece of code that compared the event's keyCode to the number 33 in router-chat.chunk.js. I know that the keycode for `Enter` is 13, so I searched for that number in the file and placed breakpoints in every function where it was mentionned.
- Then used the debugger's `Continue` button. Hit one of the breakpoints I placed. Used the `Step into` button a bunch of times and discovered that `event.keyCode == 13` was false!

The reason `event.keyCode == 13` is false is that `event.keyCode = 0`, and `event.keyCode = 0` because Firenvim just doesn't set keycodes when it creates events. I think the reason I did not set keycodes when I wrote `firenvim#press_keys` is that keyCodes are layout dependent: people with a qwerty keyboard do not have the same keycodes as people with an azerty keyboard. Moreover, [keyCode](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode) is deprecated and should not be used by websites anymore but I guess webdevs don't care about that.

Since I believe `Enter`'s keycode to be layout-independent, I'll add a special-case to `press_keys` to set the keyCode for that event.

**Comment by BlueDrink9** [comment]
That's an awesome write-up. It would have been way too complicated for me to attempt alone. I have never touched an explicit debugger in the browser. After reading write-up that comprehensive though, I feel like I could give it a reasonable shot. Thank you!

**Comment by glacambre** [comment]
Implemented and working as far as I could see. I'll try to publish a new release in the coming weeks. Thanks for the bug report! :)
