### ISSUE TITLE
[Feature Request] Support set custom css 

### ISSUE THREAD

**Issue by lolimay** [glacambre/firenvim#765]
It will be great if we can set custom css for this extension in the options page :)
For instance, the current iframe's `box-shadow: black 0px 0px 1px 1px` is hardcoded.

- OS Version: mac x86-64
- Browser Version: Google Inc. Chrome 87.0.4280.47
- Browser Addon Version: 0.1.31
- Neovim Plugin Version: 0.1.31
- What I tried to do:
- What happened:

**Comment by glacambre** [comment]
Could you describe what kind of changes you want to apply to the CSS? This would help me understand what the best way to implement this change is :).

**Comment by lolimay** [comment]
For instance, we can add some padding according our own preferences:

```css
.nvim_grid {
  padding: 10px 0;
}
```

**Comment by glacambre** [comment]
I see two issues with this:
- Computing the size of the grid is very complicated, allowing arbitrary changes to the padding/margin of elements in the frame would complicate it even more.
- We can't rely on CSS to perform changes inside the neovim frame as they won't work with the [new renderer](https://github.com/glacambre/firenvim/issues/347).
I think we need to find a better way to express GUI-level customizations (and perhaps even standardize it, so that other GUIs can benefit from it?).

**Comment by lolimay** [comment]
no problem. It does make sense! btw, looking forward to the new webGL renderer :)

**Comment by glacambre** [comment]
@lolimay Just to be clear, I'm not against allowing customizations, I just don't think CSS is the way forward. We need to come up with a proper design :)

**Comment by JW9506** [comment]
I would like to have it to modify the dimmed level for out-of-focus appearance.

**Comment by glacambre** [comment]
@JW9506 It's not exactly what you want but you can control out-of-focus appearance by using the FocusLost and FocusGain autocommands (e.g. `:au FocusLost * colorscheme slate`). I'm very reluctant to provide direct access to the CSS because it wouldn't be a standard Neovim UI thing and would expose far too much of Firenvim's internals.

Come to think of, I'll probably even replace the CSS-based dimming with colorscheme-based dimming, triggered with FocusLost and FocusGain events. This way it'll be entirely controllable with the usual tools provided by Neovim.

**Comment by JW9506** [comment]
@glacambre Sounds great, the thing that bothers me is that often time I need to shift the focus to other windows and at the same time read from the editor.
