### ISSUE TITLE
Takeover settings not respected in thunderbird

### ISSUE THREAD

**Issue by glacambre** [glacambre/firenvim#777]
>I have 'takeover': 'never' in my nvim init file, but this is not taken into account for Thunderbird and the Neovim window is always launched when starting a new message. Which is a good thing I guess, since ctrl+e doesn't work and I don't see how I would open Neovim otherwise :).

Not using Firenvim in Thunderbird didn't even cross my mind, sorry about this @Qeole :).

**Comment by Qeole** [comment]
Ahah makes sense :). To tell the truth, I had the `'takeover': 'never'` in place for Firefox, but because it was there I expected it to work for Thunderbird, too.

By the way, I guess I should find a way to dissociate my configuration options for Firefox and Thunderbird. Do you know how I can find the “URL” that is passed to the Thunderbird add-on, so I could filter on it for the `localSettings`? Or I guess one alternative would be to have global settings for TB and then filter on `http.*` for Firefox, maybe.

**Comment by glacambre** [comment]
This is now fixed in master. I'll publish a new release in a few weeks.

>Do you know how I can find the “URL” that is passed to the Thunderbird add-on, so I could filter on it for the localSettings?

I didn't but now I do: it's "about:blank?compose". Since firenvim's config rules are javascript regexes, you need to escape the question mark, like this:
```vim
let g:firenvim_config = {
        \ 'localSettings': {
                \ 'about:blank\?compose': {
                        \ 'takeover': 'always'
                \ }
        \ }
\ }
```

**Comment by Qeole** [comment]
I'll try that, thanks a lot!
