### ISSUE TITLE
How to make this work on youtube comments?

### ISSUE THREAD

**Issue by rohitkrishna094** [glacambre/firenvim#808]
- OS Version: Windows 10(64 bit)
- Browser Version: Version 87.0.4280.66 (Official Build) (64-bit)
- Browser Addon Version: 0.1.32
- Neovim Plugin Version: 0.4.3
- What I tried to do: Comment on youtube
- What happened: Not working on youtube comments section

So since this only works on textarea, it won't work on youtube? I inspected youtube comments using chrome dev tools and looks like youtube is using div ::before tag and somehow updating the text. 

1. Is there a way to get this to work on youtube?
2. Why would youtube not use semantic html like <input/> tag with type="text" or "textarea"?

**Comment by glacambre** [comment]
> Is there a way to get this to work on youtube?

It looks like having the following firenvim config is enough to make Firenvim detect the youtube comment area:
```vim
let g:firenvim_config = {
        \ 'localSettings': {
                \ '^https?://[^/]*youtu\.?be[^/]*/': {
                        \ 'selector': '#contenteditable-root'
                \ },
        \ }
\ }
```

You can use your browser's element inspector to find a uniquely-identifying css selector that you can give to firenvim in order to have it specifically look for it.

>Why would youtube not use semantic html like tag with type="text" or "textarea"?

No idea, although I would guess that this is because they want to implement features not provided by regular tags :).

**Comment by rohitkrishna094** [comment]
Thanks so much for quick reply. This totally works.
