### ISSUE TITLE
Firenvim doesn't work in brave unless shield is turned off

### ISSUE THREAD

**Issue by DragonL40** [glacambre/firenvim#852]
- OS Version: mac x86-64
- Browser Version: Google Inc. Chrome 87.0.4280.101
- Browser Addon Version: 0.1.32
- Neovim Plugin Version: 0.1.32
- What I tried to do: Use firenvim with Brave
- What happened: It doesn't work (even with <C-e> trigger) unless the shield is turned off. I have seen people who has gotten firenvim working with Brave's shield up.

**Comment by glacambre** [comment]
Hi, thanks for opening this issue :). Unfortunately, there's nothing I can do - Brave is preventing Firenvim from connecting to the neovim server. The recommended workaround steps are to disable Brave shield and install an ad blocker like uBlock Origin.

This issue was also mentioned in https://github.com/glacambre/firenvim/issues/823 - I guess I should have kept it open in order to make it easier to find. I'll close your issue and reopen #823 as it contains more information, please follow up in #823 if you have more questions/additional information :).
