### ISSUE TITLE
Can't install on Thunderbird 78

### ISSUE THREAD

**Issue by varac** [glacambre/firenvim#942]
I tried to install the TB extension from https://addons.thunderbird.net/en-US/thunderbird/addon/firenvim following the [TB installation intructions](https://github.com/glacambre/firenvim/blob/master/CONTRIBUTING.md#thunderbird).
But TB (v78) complained that this extension reqires v84 or above (which obviously relates to the firefox version, not the TB one).

Please provide a TB extension wich works with current/latest TB versions. Thanks !

**Comment by varac** [comment]
As a workaround I updated `strict_min_version` to `78` in the `manifest.json` of the downloaded extension, then it works with TB 78.

**Comment by glacambre** [comment]
As described on the thunderbird add-on store, you can't use Firenvim with Thunderbird ESR. Instead, you need to build Thunderbird yourself and apply the patches mentioned on the thunderbird add-on store. This is because Thunderbird has multiple bugs that need to be fixed before Firenvim can be made usable.

If installing Firenvim after building from source works with Thunderbird 78, that's entirely by accident and is completely unsupported :).
