### ISSUE TITLE
Environment issue with `$XDG_DATA_HOME/firenvim/firenvim`

### ISSUE THREAD

**Issue by aopom** [glacambre/firenvim#960]
Hi!
I have an issue setting up Firenvim on NixOS.
After some help on [its forum](https://discourse.nixos.org/t/using-firenvim-neovim-embedded-in-firefox-in-nixos/11623), I have set `XDG_DATA_HOME` correctly.
But it appears that :
- This command works fine (no output) : `echo 'abcde{}' | eval < .local/share/firenvim/firenvim`
- This command doesn't : `echo 'abcde{}' | .local/share/firenvim/firenvim`
Here's the relevant error :
```
E117: Unknown function: firenvim#run
```
I don't understand the difference between them. I think it's an environment issue.
Thanks for help!

- OS Version: linux x86-64
- Browser Version:  Firefox 85.0
- Browser Addon Version: 0.2.4
- Neovim Plugin Version:

**Comment by glacambre** [comment]
Thanks for going through the troubleshooting steps, this is very useful. This error indicates that the Firenvim bash script was able to run Neovim but that Firenvim does not exist in Neovim's runtime path (= the neovim plugin isn't loaded).

The simplest way to fix this is to edit .local/share/firenvim/firenvim and add `--cmd 'set rtp+=PATH/TO/GIT/CHECKOUT/OF/FIRENVIM'` to the line that execs neovim, in order to force loading of the plugin. I'm surprised this is not working by default though - how did you install the neovim plugin?

**Comment by aopom** [comment]
It indeed fixed the issue.
My installation is standard (I think), I install plugins with `vim-plug`, the plugins are here `~/.config/nvim/plugged`  and the init script is here `~/.config/nvim/init.vim`
