### ISSUE TITLE
Possibilities of displaying image

### ISSUE THREAD

**Issue by tejasvi** [glacambre/firenvim#971]
I realize this feature is a moonshot though theoretically it should be possible with canvas. I haven't dug deeper yet. How difficult would it be? My specific usecase is displaying inline rendered LaTeX.

**Comment by glacambre** [comment]
I won't implement this until there is a specific protocol for this in Neovim, but feel free to fork Firenvim and experiment with the code to implement the features you need, I'll be happy to answer any question you may have about Firenvim's architecture :).

I'm going to close this issue rather than label it as `blocked`+`neovim-feature` as I'm not certain neovim will ever get support for displaying images, even though it seems the idea hasn't been completely rejected: https://github.com/neovim/neovim/issues/12991 .
