### ISSUE TITLE
firenvim script doesn't print JSON

### ISSUE THREAD

**Issue by devanshuDesai** [glacambre/firenvim#998]
- OS Version: mac x86-64
- Browser Version: Google Inc. Chrome 89.0.4389.90
- Browser Addon Version: 0.2.4
- Neovim Plugin Version: 0.2.4
- What I tried to do: Tried running `echo 'abcde{}' | $XDG_DATA_HOME/firenvim/firenvim`
- What happened: the script runs for hours without printing an output or an error

![image](https://user-images.githubusercontent.com/37163544/111896441-de44f580-89d6-11eb-9759-5a5034f9ce78.png)

**Comment by glacambre** [comment]
Hi, thanks for going through the troubleshooting guide, this was useful :).

As you can see, you're getting an error when neovim starts. You should fix it - Firenvim can't work if there are errors during startup. This is because of constraints in both the browser APIs used to start Neovim and the way Neovim handles errors.

**Comment by devanshuDesai** [comment]
yep, that was it! I thought since it's just a warning it shouldn't make a huge
difference but I was wrong. Thanks! I'll close out the issue.

**Comment by glacambre** [comment]
Great, thanks for the update! :)
